jsonnetfile.json

Without the https remote users of this package will need to use an ssh
key to authenticate with github, with https this is not necessary
therefore it's easier to consume.
(this is the new default behavior when using jsonnet-bundler to install a dependency)
@tomwilkie

Use https remote

---

dashboards/node.libsonnet
dashboards/use.libsonnet

From https://github.com/prometheus/node_exporter/issues/269 it's noted
that `node_filesystem_free` can provide a less accurate metric for
when a fs write would fail (from full disk).
Usecase: https://github.com/coreos/prometheus-operator/pull/1299

Use node_filesystem_avail over node_filesystem_free

---

alerts/apps_alerts.libsonnet

```
level=warn 
ts=2018-05-09T04:41:12.860180827Z 
caller=alerting.go:220 component="rule manager" 
alert=KubeDeploymentGenerationMismatch 
msg="Expanding alert template failed" 
err="error parsing template __alert_KubeDeploymentGenerationMismatch: template: __alert_KubeDeploymentGenerationMismatch:1: function \"labels\" not defined" 
data="unsupported value type"
```

alerts: fix typo on KubeDeploymentGenerationMismatch

---

rules/rules.libsonnet

Related to https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/17
Excludes non-scheduled pods (evicted, completed etc.) from request calculation.

Only include scheduled pods in the resource usage calculation

---

alerts/apps_alerts.libsonnet

These alerts mirror the alerts for Deployments
- replicas ready != replicas
- observed generation != metadata generation

Add alerts for StatefulSets

---

alerts/system_alerts.libsonnet
config.libsonnet

This isn't perfect, as it won't alert if one random cert with very low valid period is used once vs certificates with long life thousands of times.  Alternative would be to let users pick from the hard coded buckets, but that seems fragile.  WDYT, @brancz?

Use histogram for cert expiry alerts, make it configurable.

---

lib/promgrafonnet/gauge.libsonnet
lib/promgrafonnet/numbersinglestat.libsonnet

I had broken singlestats on the node dashboard, because my datasources aren't called Prometheus, but DigitalOcean.

Change datasource to $datasource in gauge helpers

---

Makefile
alerts/add-runbook-links.libsonnet
alerts/alerts.libsonnet
lib/utils.libsonnet
runbook.md
runbooks/README.md

I noticed that the monitoring-mixin rules/alerts don't come with any runbook links defined, which I feel is a missed opportunity. For an alert detecting standard problems, a link to a  remediation (or at least description of the problem being measured) is very welcome.
I have not altered the ksonnet files to add the runbook annotations that are missing (compared to prometheus-operator rules), nor do I have a plan to automatically generate this markdown file from the ksonnet files if that's possible or desirable.
This is an initial effort, and I won't feel bad if someone does this better. I had not added meaningful descriptions to these alerts, but I hope that it can be improved over time.

Add Initial Runbook Readme.md

---

config.libsonnet
dashboards/add-dashboard-uid.libsonnet
dashboards/dashboards.libsonnet
dashboards/node.libsonnet
dashboards/pods.libsonnet
dashboards/resources.libsonnet
dashboards/statefulset.libsonnet
dashboards/use.libsonnet
lib/grafana.libsonnet

This PR adds a randomly generated ID to each dashboard, so that drill-down links can work. Beyond that it also means that even if Grafana gets re-deployed links will be stable, so dashboards links can be shared.
One thing I wonder about is, that I could not find the "legendLinks" used in the dashboards in the Grafana dashboard definition. Was this possibly available in Grafana v4 but removed in v5?
@tomwilkie @metalmatze

Add dashboard IDs in order to make links work

---

alerts/apps_alerts.libsonnet
runbook.md

Part of #24; haven't tried the more advanced alerts mentioned in the blog yet.

Basic cron job alerts.

---

config.libsonnet
rules/rules.libsonnet

Currently the host networking interface is locked to having to be `eth0`. While it's a sensible default it should be configurable.
@tomwilkie @metalmatze

Make host network interface selector configurable

---

alerts/add-runbook-links.libsonnet
dashboards/add-dashboard-uid.libsonnet

This ensures, that only actual alert definitions get the runbook added, and instead of `super.alert` it uses the passed `rule` variable.
(also formats the repo once, it seems we missed to do this at some point)
@tomwilkie

Ensure rule is an alert when adding runbook link

---

alerts/apps_alerts.libsonnet

Some of our deployment upgrades can take a while as they have to shuffle a bunch of data around.

Bump replica mismatch alert to 1h.

---

.circleci/config.yml
dashboards/node.libsonnet

#49 broke the dashboard build, this fixes it. This just moves the items from the `legend` object to the "top level" parameters and prefixes them correctly as grafonnet requires it.
@tomwilkie @metalmatze 
cc @mrsiano

dashboards: Fix node dashboard legend

---

config.libsonnet
dashboards/node.libsonnet
dashboards/resources.libsonnet
dashboards/use.libsonnet

* dashboards: jsonnet fmt
* USE (Nodes): Add node grouping and filter
Currently the "Disk Utilisation" expression references the "node" label but
it is not present in the node_filesystem_* metrics.
This fixes it by grouping with the node_namespace_pod:kube_pod_info:
recording rule.
Finally it adds the "$node" filter which was ignored previously.
* USE (Nodes): use fstypeSelector
This prettifies the Disk Capacity expression and references the
fstypeSelector for filtering file systems.
* Nodes: deduplicate devices in Disk Space Usage calculation
If node exporter is deployed as a container, this currently sum all bind
mounts despite being the same source device.
This fixes it by deduplicating the values.
* config: add global filesystem selector
Quite some expressions reference a set of file …

Disk usage expression enhancements

---

dashboards/node.libsonnet

Currently, the gauge does not work if there are multiple
file systems attached to a node.
This fixes it by replacing it with a graph.
This also fixes the alignment of the cpu and memory rows.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1622387
/cc @brancz @metalmatze

dashboards/node: Fix Disk Space Usage gauge

---

alerts/apps_alerts.libsonnet

https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase
Essentially is something is evicted, or exits with non-zero, it gets rescheduled. Now, the failed pod sticks around until `--terminated-pod-gc-threshold`.
> The only exception to this rule is that Pods with a phase of Succeeded or Failed for more than some duration (determined by terminated-pod-gc-threshold in the master) will expire and be automatically destroyed
```
--terminated-pod-gc-threshold int32     Default: 12500
Number of terminated pods that can exist before the terminated pod garbage collector starts deleting terminated pods. If <= 0, the terminated pod garbage collector is disabled.
```
This is causing us some alerts like:

Ignore failed pods for KubePodNotReady

---

dashboards/node.libsonnet
dashboards/use.libsonnet
rules/rules.libsonnet

This allows reusing node disk space calculations in dashboards
as well as in various alerts.
Fixes #71
Signed-off-by: Sergiusz Urbaniak <sergiusz.urbaniak@gmail.com>

dashboards: reuse disk space usage metrics as a recording rule

---

dashboards/resources.libsonnet
rules/rules.libsonnet

In Kubernetes 1.11 the parent cgroup metrics of all containers in a Pod
also has the `namespace` and `pod_name` labels set. The dashboards
previously summed all time-series that have these labels, however, that
caused primarily memory to be doubled.
As a result, this also removes the non-Pod metrics from the cluster
dashboard.
Before:
After:
@metalmatze @tomwilkie

*: Fix usage of duplicate cAdvisor time-series

---

alerts/storage_alerts.libsonnet
config.libsonnet

Currently the KubePersistentVolumeFullInFourDays check uses 1 hour
of sampling data to predict 4 days of volume fill up. To make the
check more sophisticated the sampling time is now configurable and
defaults to 6 hours.
Also to prevent already deleted volumes from alerting we check, if
there is most recent data of a volume before predicting its status.
Fixes #54

Make volume prediction more sophisticated

---

alerts/storage_alerts.libsonnet

Fix the typo found in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/72#issuecomment-418768321

Fix typo in KubePersistentVolumeFullInFourDays message

---

alerts/system_alerts.libsonnet
config.libsonnet

This commit changes the Kubelet Pod limit of 110 into a
constant that is templated from the `_config` object.
cc @mxinden @metalmatze 
Fixes: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/81#discussion_r215987116

alerts: make kubelet pod limit a templated const

---

dashboards/resources.libsonnet

`kube_pod_container_resource_limits_memory_bytes` metric comes from kube-state-metrics which uses `container` as label. 
Neighboring metrics come from cadvisor which uses `container_name`. This lead to error when C&P, looking into group by labels shows discrepancy :P 
@brancz @tomwilkie

Fix memory quota query

---

dashboards/resources.libsonnet

It currently only shows 1.42 Bil instead of 1.42 Gi

Set the cluster resource namespace’s memory to correct format

---

alerts/resource_alerts.libsonnet

This fixes an issue with the KubeQuotaExceeded alert when having some hard limit set to 0 (for instance services.loadbalancers set to 0).
The alert was triggering with +Inf or NaN results.

alerts: fix KubeQuotaExceeded potential division by zero

---

alerts/apps_alerts.libsonnet

As a per second restart rate for a lot of pods is quite small the KubePodCrashLooping message often looks like
```
{{namespace}}/{{pod}} is restarting 0.00 / second
```
As this information gives about no extra value (besides the fact, that its restarting), this PR increases the printed value to a 5-minute rate over the last 15 minutes of data and increases the decimal places to 3.

Use 5 minute range for KubePodCrashLooping message

---

alerts/storage_alerts.libsonnet

Only trigger `KubePersistentVolumeFullInFourDays` alert when disk usage is above 85 %.
Currently waiting on a cluster for testing these changes, as my personal cluster doesn't have these metrics available.
Closes #99 
/cc @mxinden

Only fire VolumeFullInFourDays when over 85% utilization

---

alerts/resource_alerts.libsonnet

Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

Reference the pod_name instead of container name

---

alerts/apps_alerts.libsonnet

@tomwilkie @brancz @metalmatze 
`job` is always `kubeStateMetricsSelector`

Reference the right label for KubeJob* alerts

---

Makefile
alerts/storage_alerts.libsonnet
tests.yaml

This will format the current bytes as e.g. `324Mi` in the alerts message.
Fixes #100 
/cc @mxinden

Use humanize1024 to format alert message

---

alerts/storage_alerts.libsonnet
tests.yaml

This is the first time our CI found a bug in an alert. :tada: 
It turns out that #101 and #102 are incompatible and the `KubePersistentVolumeFullInFourDays` needs to be fixed.
Instead of using `...used_bytes` is moved to `...available_bytes` to show the percentage of available storage rather than the used percentage.
We cannot show the number of available bytes as we compute the percentage within the alert and thus showing that now in the message.
/cc @brancz

Fix KubePersistentVolumeFullInFourDays again

---

rules/rules.libsonnet

PR #65 updated the syntax for rules from node-exporter to v0.16.0. This is a small fixup for some missed metrics (which break e.g. some of the K8s / Compute Resources / Cluster Headlines)

Fix node_filesystem_* for node-exporter 16.0 syntax

---

alerts/resource_alerts.libsonnet
config.libsonnet

This PR adds an optional selector used for the CPUThrottlingHigh alert.
The selector can be used to disable the alert on some noisy namespaces.

alerts: add optional selector for CPUThrottlingHigh

---

config.libsonnet
rules/rules.libsonnet

If your cluster runs with different diskselectors the recording rules for disks are broken (e.g. KVM default is vd[a-z]). This PR makes the selector configurable

Make disk device name selector configurable

---

alerts/system_alerts.libsonnet

IMHO deploying a misconfigured workload is not an indication of the clusters health, hence exclude all 4XX errors

Only trigger KubeClientErrors on 5xx status codes

---

dashboards/node.libsonnet

Currently the `node_cpu_seconds_total` metric values are averaged per cpu core. As the labels are `app controller_revision_hash cpu instance job mode namespace pod pod_template_generation` (especially `cpu` and `mode`) the `avg by(cpu)` will calculate the average by all modes (and multiply it by 100, which is also wrong as the dashboard is percentage in 0-1 syntax).
This PR fixes the graph

Fix Usage per Core panel in Node dashboard

---

alerts/resource_alerts.libsonnet

The CPUThrottlingHigh alert currently fires on pod and container level. That means that if a container gets throtteled we not only alert on the alert but also on the pod.
As we always have the container available, we should simply alert on the container directly and exclusively, by filtering to `container_name!=""` in the expression.
Furthermore is the message for this alert written so that it uses `{{  $labels.container_name }}`. For the pod level alert we don't have these values and thus the message is broken.
Here's both levels of alerts:
Here's only the container directly:

Alert directly on containers for CPUThrottlingHigh alert

---

alerts/system_alerts.libsonnet

Update the `KubeClientCertificateExpiration` alert description to more
accurately reflect the meaning of the metric. This metric is used to
observe the expiration of client certificates used for authentication,
and in this case, for authentication to the apiserver. It does not mean
that the apiserver's server certificate is expiring which can be implied
by the existing message.
I initially requested the change in https://github.com/coreos/prometheus-operator/pull/2058, but was referred here. Also submitted a request to the helm chart https://github.com/helm/charts/pull/10840
Reference: https://github.com/kubernetes/kubernetes/pull/50387

Update certificate expiration alert message

---

config.libsonnet

Instead of selecting specific interfaces and try to match as much as possible, we should rather exclude the we don't want to include.
This was fixed downstream for us and we want to contribute it upstream: https://github.com/openshift/cluster-monitoring-operator/pull/226
/cc @brancz @tomwilkie

Improve hostNetworkSelector by excluding the ones we don't want

---

alerts/system_alerts.libsonnet

Handle perpetually firing KubeVersionMismatch when using Amazon EKS

---

README.md
config.libsonnet
dashboards/node.libsonnet
dashboards/persistentvolumesusage.libsonnet
dashboards/pods.libsonnet
dashboards/resources.libsonnet
dashboards/statefulset.libsonnet
dashboards/use.libsonnet

This way people can tell which all dashboards came from the mixin as opposed to their other internally-developed dashboards
* allow prefix to be empty string

use shared prefix for all dashboard names

---

dashboards/use.libsonnet
rules/rules.libsonnet

Currently the node:node_memory_utilisation:ratio calculates the
node memory usage normalized by the whole cluster memory. This
change fixes the normalization to actually be per node.

Fix node:node_memory_utilisation:ratio rule

---

dashboards/resources.libsonnet

This PR stacks the pod and namespace graphs, reporting RSS, cache and swap memory usage separately. The memory tables report RSS, cache and swap memory in addition to total memory usage per container/pod.
This addresses #152 .

Separate pod memory usage by RSS/cache/swap

---

dashboards/defaults.libsonnet

When having a lot of namespaces in the cluster dashboard the tooltip becomes to big and the user might not be able to see the most interesting value.
Therefore we override all dashboard tooltips to only show the single value that the cursor currently hovers.
Previously:
New:
/cc @brancz @tomwilkie

Override all tooltips to have single values

---

README.md
config.libsonnet
dashboards/node.libsonnet
dashboards/persistentvolumesusage.libsonnet
dashboards/pods.libsonnet
dashboards/resources.libsonnet
dashboards/statefulset.libsonnet
dashboards/use.libsonnet
rules/rules.libsonnet

If you are running Thanos (with external labels for clusters)
or Cortex (with a cluster label) use these dashboards to have an
overview of all the clusters in your Kubernetes environment.
The cluster label is configurable and defaults to 'cluster'.
There is a feature toggle, (showMultiCluster) that is off by default.
Enabling multiCluster will show 2 new multiCluster dashboards and
show clusters pickers on all the rest.
Note: you need head of grafana/jsonnet-libs, so jb update
Co-authored-by: Bob Cotton <bob.cotton@gmail.com>

Add support for multi-cluster dashboards.

---

alerts/system_alerts.libsonnet

This commit splits the KubeAPIErrorsHigh alert into multiple
parts to handle overall errors and individual verb-resource errors
correctly. Until now `code` was part of the labelset used for
summation, which resulted in flapping alerts between 0% and 100%.
Fixes #146.

Fix KubeAPIErrorsHigh flapping

---

alerts/system_alerts.libsonnet
alerts/utils.libsonnet

Display time till expiration in KubeClientCertificateExpiration message
annotation either in days or hours, depending on users configuration.

alerts/system_alerts: Display cert expiration in days or hours

---

rules/rules.libsonnet

In our cluster we have a bunch of cron jobs. Currently, with the existing query, it appears to be counting the pods that are already completed or failed.
As far as I understood, I believe the overcommit should count only the pods in Pending or Running state.
This change should be applied to the line 64, where it counts the CPU overcommit. It was changed in the PR #18.
I did not change them all because I wan't to check where this is a valid change or not, since it is not very clear to me and my colleagues.

Count overcommit memory only for pods in Pending or Running status

---

alerts/system_alerts.libsonnet

Amazon EKS doesn't rely on client certificate to manage authentification. So client certificate expiration alerts are always on as apiserver_client_certificate_expiration_seconds_bucket{} always returns 0
Proposed solution is to check that there are non 0 values on this metric before checking the future expiration date

Silent client certificate expiration alert on EKS

---

alerts/resource_alerts.libsonnet

This PR fixes the label values on the Kube(CPU|Mem)Overcommit alert

Fix kube overcommit expression

---

dashboards/use.libsonnet

This was probably a miss in the creation of cluster-level dashboard. Should be showing legend with the custom "clusterLabel" same as other panels in this dashboard.
Figure (screenshot of error):

Fix bug in legend of Multi-cluster USE dashboard

---

alerts/utils.libsonnet

Instead of printing the time as an integer, print it as a floating point
decimal with precision of one. When humanizing 5400 (1.5 h), with this
patch, `1.5 days` instead of `1 days` is printed.
This is a small follow up to https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/168.

alerts/utils: Print humanized time in floating point decimal format

---

rules/rules.libsonnet

In #154 we changed the memory request rule to only take running or pending pods into account, but we forgot to change it for CPU.
This PR changes the CPU requests to only take running and pending pods into account too.
Tested by running the old and new query next to each other both with namespaces containing completed Pods and only Pending|Running pods.
This was reported to us in https://bugzilla.redhat.com/show_bug.cgi?id=1691893
/cc @brancz @squat

Count overcommit CPU only for pods in Pending or Running status

---

rules/rules.libsonnet

I believe this is a result of node-exporter updating the metric from `node_disk_io_time_ms` to the current `node_disk_io_time_weighted_seconds_total`
Since the new metric returns its value in seconds, the division by 1,000 is no longer required.

Fix node_disk_saturation rules (should return seconds).

---

.circleci/Dockerfile
.circleci/config.yml
config.libsonnet
dashboards/resources.libsonnet
rules/rules.libsonnet

Add Views to look at Workloads. The idea of a Workload is an abstraction between a Namespace and 
a Pod, generally what is in a Deployment/StatefulSet/DaemonSet. The problem with the current `Compute Resources / Namespace` dashboard is that in a namespace with lots of Pods it becomes useless due to the amount of pods on single graphs or in one table. The Workload abstraction allows you to reason about the general types running in that namespace easily, and drill down to a single misbehaving service.
Two new dashboards are added:
* `Compute Resources / Workloads by Namespace` - A view of all the Workloads in a namespace. You can drill down to the single workload level.
* `Compute Resources / Workload` - A view of all the pods in a Workload. You can drill down to the Pod dashboard. …

Workload dashboards

---

dashboards/pods.libsonnet

Follow up for #178. We missed to actually interpolate the templated expr string.
Works now, tested with kube-prometheus.
/cc @desaintmartin @csmarchbanks

Add string interpolation for Pods restart expr

---

dashboards/node.libsonnet
dashboards/pods.libsonnet

Changes to Nodes:
* cpu cores added to system load graph to provide context for load1, load5, load15
Changes to Pods:
* added cached memory
* added cpu requests and limits
* added network Transmitted (prev only showed received)
* added new panel to show container restarts
* fix Pod's cpu usage query to hide containers that weren't selected in dropdown
Figure (below) - Nodes dashboard showing 32 "logical cores" at left, same as number of cpus in legend at right
Figure (below) - Pods dashboard with new bits circled in red

Some tweaks to Nodes and Pods dashboard

---

dashboards/persistentvolumesusage.libsonnet

The current PV dashboard i've made does not show enough information, only percentage of used space/inodes.
Here is a new version where one has absolute metrics about free/used space, and an added gauge.

Persistent Volumes Usage dashboard: Change to show used/free space/inodes, add gauges.

---

dashboards/node.libsonnet
rules/rules.libsonnet

diskSpaceUsage was showing all devices of current k8s master/worker instead of current selected instance
before:
after:

disk usage per instance

---

alerts/resource_alerts.libsonnet
alerts/system_alerts.libsonnet
dashboards/pods.libsonnet
dashboards/resources.libsonnet
dashboards/statefulset.libsonnet
rules/rules.libsonnet

I went through this list and so far I only came across this one metric which has had it's suffix added.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#removed-and-deprecated-metrics
Am I missing something here?
Closes #182

Moving metrics to Kubernetes 1.14

---

rules/rules.libsonnet

I'm not 100% certain that wrapping these queries for the `group_left ` with `max()` solves the problem, but that's how I understood the original report: https://bugzilla.redhat.com/show_bug.cgi?id=1706476
/cc @brancz
Note: This is a fix against the release-0.1 branch. Once this is merged we need to kind of cherry-pick this into master.

Use max() against many-to-many on group_left on label_name

---

dashboards/node.libsonnet

This involves removing max from the associated queries. The max in the existing queries is hiding some information. [Discussion in slack](https://kubernetes.slack.com/archives/CAX9GU941/p1548439002093700).

Split network panels on node dashboard out by device.

---

alerts/system_alerts.libsonnet
config.libsonnet

This is the equivalent of https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/209 for the `master` branch

Allow a configurable values for warning and critical with defaults for alerting on KubeAPILatencyHigh

---

rules/rules.libsonnet

[This change here](https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/4ae5fc9e3fa90113046439dc6645ce1af9ef588b#diff-8df69bc7655ece61718c18db0cbc990cL163) has caused the kubernetes-mixin to regress for us since we use `instance` as a pod label. Since the default podLabel is already `pod` this change should be a noop for most deployments.
Signed-off-by: Jacob Lisi <jacob.t.lisi@gmail.com>

Revert label_replace for kube node info metric

---

alerts/system_alerts.libsonnet
config.libsonnet
dashboards/node.libsonnet

The p99 default limit triggers a little too often some of the clusters we run so while the default is pretty fine for most, in some cases it is useful to change it.

Allow a configurable value with a default for alerting on KubeAPILatencyHigh

---

dashboards/pods.libsonnet

The pods dashboard uses a hardcoded rate interval of 1m in the CPU and Network I/O panels. A rate interval should be at least four times the scrape interval in Prometheus, in order to avoid flakes in the graph (see https://github.com/prometheus/prometheus/issues/4229#issuecomment-395113148). This means that the scrape interval for the source data would have to be 15s in order for the graph to display reliably. This commit makes the rate configurable and so allows the user to select a longer interval if necessary.
Closes #213

Increase the pods dashboard query rate

---

README.md

I was missing having a quick link to CI. So here it is!

Add the CircleCI build badge to README

---

dashboards/node.libsonnet

I've been using the node dashboard as a boilerplate for a node_exporter based VM monitoring and realized that the Disk Space Usage panel doesn't provide any information which disk is using space, because of a missing label in the legend.
If having multiple disks in a system is not intended for this dashboard please proceed with closing the PR.

Add device label to legend of Disk Space Usage panel

---

alerts/system_alerts.libsonnet

Replace hardcoded job filter `{job="apiserver"}` with `{%(kubeApiserverSelector)s}` in `KubeClientCertificateExpiration` alerts expression

Fix System Alerts hardcoded job name in KubeClientCertificateExpiration alert expression

---

README.md

Current Jsonnet snippet is not valid:
STATIC ERROR: mixin.libsonnet:9:15: expected token OPERATOR but got "."
Breaking change was introduced in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/143/commits/6b82a1d445e2d91870c3522e08df27b0d0cc3702#diff-04c6e90faac2675aa89e2176d2eec7d8R123

Fix Grafana dashboard overrides example in README

---

alerts/system_alerts.libsonnet
config.libsonnet

I'm using GKE and the metrics `kubernetes_build_info` returning series with label `job=coredns`:
```
kubernetes_build_info{buildDate="1970-01-01T00:00:00Z",compiler="gc",endpoint="http-metrics",gitCommit="$Format:%H$",gitTreeState="not  a git  tree",gitVersion="v1.5.2-beta.0+$Format:%h$",goVersion="go1.10.3",instance="10.32.2.4:10055",job="coredns",major="1",minor="5+",namespace="kube-system",platform="linux/amd64",pod="kube-dns-564d97dc9c-fgqvj",service="prometheus-coredns"} | 1
-- | --
kubernetes_build_info{buildDate="1970-01-01T00:00:00Z",compiler="gc",endpoint="http-metrics",gitCommit="$Format:%H$",gitTreeState="not  a git  tree",gitVersion="v1.5.2-beta.0+$Format:%h$",goVersion="go1.10.3",instance="10.32.3.5:10055",job="coredns",major="1",minor="5+",namespace="kube-system",platform="li …
```

Fix KubeVersionMismatch not correct

---

Makefile

From the [v0.13.0](https://github.com/google/jsonnet/releases/tag/v0.13.0) release notes:
> If you've got scripts that run jsonnet fmt, you will need to delete the space from them.

Update Makefile to support jsonnet >= 0.13

---

rules/rules.libsonnet

Remove duplicate rule 'namespace:container_cpu_usage_seconds_total:sum_rate'

---

dashboards/node.libsonnet

node exporter 0.16.0 introduce metric name change, include:
```
node_disk_io_time_ms -> node_disk_io_time_seconds_total
```
but the yaxe still be ms in the config.
Checked source file https://github.com/prometheus/node_exporter/blob/master//collector/diskstats_linux.go#L118 , it should be seconds.

Fix iotime yaxe

---

dashboards/resources.libsonnet

`container_memory_usage_bytes` is a metric which can be fluctuating a lot as it contains cached memory. This can cause confusion when looking at memory usage of a pod. It is also not used by any k8s mechanism which just adds more confusion. Replacing it with `container_memory_working_set_bytes` should mitigate those issues as it comes from the same source as data used by k8s scheduler when placing pods across a cluster.

dashboards: use container_memory_working_set_bytes instead of container_memory_usage_bytes

---

alerts/apps_alerts.libsonnet

I have a completed job, which previously failed 3x times:
```
status:
completionTime: "2019-08-27T05:31:06Z"
conditions:
- lastProbeTime: "2019-08-27T05:31:06Z"
lastTransitionTime: "2019-08-27T05:31:06Z"
status: "True"
type: Complete
failed: 3
startTime: "2019-08-27T05:29:00Z"
succeeded: 1
```
status metric returns:
```
kube_job_status_failed{".."} 3
```
although job has completed:
```
kubectl get job                       
NAME             COMPLETIONS   DURATION   AGE
job-name   1/1           2m6s       3d
```
So the alert never closes.
Ref https://github.com/kubernetes/kube-state-metrics/issues/367
The metric `kube_job_failed` is based on last job condition, so I think it should give us an alert which will close:
https://github.com/kubernetes/kube-state-metrics/blob/master/internal/store …

Fix KubeJobFailed alert

---

alerts/apps_alerts.libsonnet

Kubernetes Jobs when a pod fails, creates a new Pod and leaves the failing pod in not ready state. This is a normal behaviour and shouldn't trigger a critical alert. 
This PR filters out Job pod's from `KubePodNotReady` alert.

Fix KubePodNotReady alert for Jobs

---

dashboards/statefulset.libsonnet

A small fix for Kubernetes / Statefulsets dashboard.

Fix Kubernetes / Statefulsets namespace variable typo

---

alerts/system_alerts.libsonnet
config.libsonnet

As discussed in this issue: https://github.com/helm/charts/pull/16157#issuecomment-521244633
I need the fix to be on Kubernetes 1.13 also, so I'm creating this PR to backport the fix to release-0.1.

Fix false positive kubeversionmismatch for Kubernetes < 1.14

---

dashboards/resources.libsonnet
dashboards/use.libsonnet

The 'cluster' picker atop these dashboards can get 'cluster' label values more cheaply by querying a lower cardinality metric.
Without this change, we're seeing max payload sizes exceeded returning the `label_values(node_cpu_seconds_total, cluster)` query from cortex to grafana
Submitting this PR against the release-0.1 branch to apply to kubernetes 1.13

use lower cardinality metric for 'cluster' picker query

---

alerts/system_alerts.libsonnet

`ksm_scrape_error_total metric` was removed from kube-state-metric in the
release v1.5.0.
https://github.com/kubernetes/kube-state-metrics/blob/b31a4006d5a5fbe6642902a38e3b27fd96a1331a/CHANGELOG.md#v150--2019-01-10
Not sure if we want to rewrite this alert using another metric, but I guess we can do this in a follow up? cc @metalmatze @brancz

alerts/system_alerts.libsonnet: Remove broken alert

---

alerts/apps_alerts.libsonnet

When dividing a lot of decimals are normally present in the result.
This change uses the Prometheus filter humanizePercentage to minimize
the number of decimals, and also removes the conversion to percentage in
the calculation of the result itself.

humanizePercentage to get rid of many decimals.

---

README.md
alerts/resource_alerts.libsonnet
alerts/storage_alerts.libsonnet
alerts/system_alerts.libsonnet
runbook.md
tests.yaml

When dividing a lot of decimals are normally present in the result.
This change uses the Prometheus filter humanizePercentage on all
remaining percentage calculations to minimize the number of decimals,
and also removes the conversion to percentage in the calculation of
the result itself.

humanizePercentage for remaining $values

---

lib/promgrafonnet/promgrafonnet.libsonnet

An update to the go-jsonnet library spotted this reference to a missing file.

Remove reference to missing file

---

README.md

The URL to the KEP is outdated (now has creation date `20181106` in it).
I suggest to link to the issue instead the KPE. It includes the link to the KEP as well and gives an better overview (which is also more up to date).

Readme: "metrics overhaul" link updated (now to issue)

---

dashboards/kubelet.libsonnet

* Add a cluster label to Kubelet dashboards to filter results in multi-cluster setups
Similar to: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/242

Add missing cluster filter to Kubelet dashboard

---

alerts/apps_alerts.libsonnet
runbook.md

Resolves #271 
Adds an alert when a pod cannot be in a ready state due a container being in waiting state.
Container could be in any of `ContainerCreating|CrashLoopBackOff|ErrImagePull|ImagePullBackOff|CreateContainerConfigError|InvalidImageName|CreateContainerError` these states.

container in waiting state alert

---

alerts/system_alerts.libsonnet

When nodes fail to renew their lease within a specified time limit
determined by the cluster or by administrative configuration, the
node is tainted and stateless workloads that do not tolerate the
taint will be terminated and recreated elsewhere. This is a serious
condition (often indicating network partition or total node failure)
and should result in an alert within a very short time period.
Clusters experiencing frequent unreachable nodes are considered
misconfigured and the cluster threshold for unreachable should be
increased, which should make a quick alert trigger reasonable.
Spawned as a follow up to #236

alerts: Fire an alert if a node is tainted as unreachable

---

dashboards/resources.libsonnet
rules/node.libsonnet

Use modern kernel "MemAvailable" metric when possible.
* Update recording rule name.
* Fallback to old MemFree+Buffers+Cached method for older kernels.
* Also include Slab memory[0].
[0]: https://github.com/prometheus/node_exporter/issues/1519#issuecomment-542025507

Update node memory metrics

---

dashboards/resources.libsonnet

* Memory Usage graph filters by $node, which isn't present directly in container_memory_working_set_bytes, but is in the recording rule added by
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/274
* It appears #274 fixed the Memory Quota table, but missed fixing the usage graph

Fix Compute Resources Node Pods Memory Usage

---

dashboards/resources.libsonnet

* Fix Compute Resource networking panels to filter by `$cluster`. This is important when showMultiCluster=true, bc the network panels are causing fanout to all clusters, erroneously showing an aggregate across all (CPU and mem do not), and may load many pods in tables (slow)
* Fix "Compute Resources / Workload" network panels to respect the `$workload` filter
* Fix "Compute Resources / Namespace (Workloads)" to use `$datasource` instead of a hardcoded "prometheus". Also fix CPU and memory panels to filter based on workload type
Related: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/248

Fix issues in Compute Resource network panels

---

dashboards/network-usage/cluster-total.libsonnet
dashboards/network-usage/namespace-by-pod.libsonnet
dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/network-usage/pod-total.libsonnet
dashboards/network-usage/workload-total.libsonnet

Fix network-usage dashboards to add tagging with tags set in config\
Fixes #286

add missing tags on network usage dashboards - fixes #286

---

jsonnetfile.json

Use `grafana/jsonnet-libs` instead of `kausalco/public` which silently redirects to former.
/cc @brancz @s-urbaniak

Fix dependency for grafana-builder

---

alerts/apps_alerts.libsonnet

Fix err msg found duplicate series for the match group for KubePodNotReady alert. Here is my stack trace:
`Error executing query: found duplicate series for the match group {namespace="default", pod="nginx-dbddb74b8-vks5q"} on the right hand-side of the operation: [{__name__="kube_pod_owner", endpoint="http", instance="X.X.X.X:8080", job="kube-state-metrics", namespace="default", owner_is_controller="true", owner_kind="ReplicaSet", owner_name="nginx-dbddb74b8", pod="nginx-dbddb74b8-vks5q", service="prometheus-operator-kube-state-metrics"}, {__name__="kube_pod_owner", app_kubernetes_io_instance="prometheus-operator", app_kubernetes_io_managed_by="Tiller", app_kubernetes_io_name="kube-state-metrics", helm_sh_chart="kube-state-metrics-2.4.1", instance="X.X.X.X:8080", …

[apps_alerts] - Fix err msg "found duplicate series for the match group"

---

dashboards/apiserver.libsonnet

As WATCH verbs always have a request duration of 1 minute the
dashboard panels are useless, when the resource is included (normal
requests are typically in ms range)
Signed-off-by: Christian Beneke <c.beneke@wirelab.org>

Exclude WATCH verbs from apiserver latency panel

---

alerts/apps_alerts.libsonnet

This issue
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/215
turned a "Failed" pod into a "PodNotReady". The creator of the PR wanted this for his evicted pods. I believe this is not correct. I would suggest looking at 
```
kube_pod_container_status_terminated_reason{reason!="Completed"}
OR
kube_pod_container_status_terminated
```
to build a metric if people need it. Why are we reverting? Because any failed pod will now trigger this alert, since [pods stay in the API for quite a long time](https://stackoverflow.com/questions/51234378/why-do-pods-with-completed-status-still-show-up-in-kubctl-get-pods) and therefore any failed pod == PodNotReady.
Failed pods occur all the time. Build systems, batch processing, etc.

revert failed pod marked as NotReady

---

alerts/kube_apiserver.libsonnet
rules/kube_apiserver.libsonnet

We can apply simple anomaly detection based on average and standard
deviantion of metrics for each type of request hitting apiserver.
This should limit reliance on static threshold value which can vary a
lot in different situations.
This is largely based on @brian-brazil article from https://prometheus.io/blog/2015/06/18/practical-anomaly-detection/
/cc @brancz @s-urbaniak

apply simple anomaly detectionto KubeAPILatencyHigh alert

---

rules/apps.libsonnet

Sometimes the left side of these queries has more than one matching vector for
a given vector on the right side, such as when the pod has two containers. This
caused the namespace:kube_pod_container_resource_requests_memory_bytes:sum and
namespace:kube_pod_container_resource_requests_cpu_cores:sum rules to fail
evaluation with the following error:
Error executing query: multiple matches for labels: many-to-one matching
must be explicit (group_left/group_right)"
This commit reverts a recent change where `group_left` was removed:
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/306#pullrequestreview-327321333

Re-add group_left in namespace resource requests metrics. Fixes: #308

---

Makefile
alerts/kube_apiserver.libsonnet
config.libsonnet
jsonnetfile.json

I want to start a discussion on having a SLO for the apiserver and its error rate.
By default I simply settled for 99% availability and generated all the recording rules and alerts for multi burn rate alerts.
/cc @brancz @csmarchbanks @tomwilkie @gouthamve @povilasv 
Here's the output for the generated rules as a reference.
```yaml
"groups":
- "name": "kube-apiserver-error"
"rules":
- "alert": "ErrorBudgetBurn"
"annotations":
"runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-errorbudgetburn"
"expr": |
(
status_class_5xx:apiserver_request_total:ratio_rate1h{job="kube-apiserver"} > (14.4*0.010000)
and
status_class_5xx:apiserver_request_total:ratio_rate5m{job="kube-apiserver"} > (14.4*0.010000)
)
or
( …
```

Introduce apiserver SLO of 99% with multiple burn rate alerts

---

dashboards/network-usage/cluster-total.libsonnet
dashboards/network-usage/namespace-by-pod.libsonnet
dashboards/network-usage/namespace-by-workload.libsonnet

The table headers on the network tables are not working:
Looking at the generated dashboard JSON, the `pattern` field of each column was empty. When I looked at the code for `table_panel.libsonnet`, I noticed it take the `pattern` from `field`:
```jsonnet
addColumn(field, style):: self {
local style_ = style { pattern: field },
local column_ = { text: field, value: field },
styles+: [style_],
columns+: [column_],
},
```
So I simply set the `field` to be the right name of the template to fix the bug:

fix table headers in network graph

---

dashboards/network-usage/cluster-total.libsonnet

Add 2 new panel - retransmits out of all out segments and syn retransmits out of all syn segments. Added links to both panels to make it easier for users to understand why they should care (I, for example, didn't knew and had to google it). I do wonder why we have one node with 50% retransmits out of all syn segments and if we have an issue or a bug with my query :)
close #320

added retransmits to cluster network dashboard

---

dashboards/kubelet.libsonnet

Fixes #335
- `kubelet_runtime_operations` is deprecated
- replace with `kubelet_runtime_operations_total`

Fix "instance" template var in kubelet dashboard

---

dashboards/apiserver.libsonnet
dashboards/controller-manager.libsonnet
dashboards/kubelet.libsonnet
dashboards/network-usage/cluster-total.libsonnet
dashboards/network-usage/namespace-by-pod.libsonnet
dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/network-usage/pod-total.libsonnet
dashboards/network-usage/workload-total.libsonnet
dashboards/persistentvolumesusage.libsonnet
dashboards/pods.libsonnet
dashboards/proxy.libsonnet
dashboards/scheduler.libsonnet
dashboards/statefulset.libsonnet
dashboards/windows.libsonnet

There can be multiple  datasources of `type: prometheus` available (i.e.
Prometheus and Thanos) and a datasource can be marked as a `default`
which makes any dashboard using the `default` as a datasource
automatically use the one chosen by the user.
This PR makes the selector on the dashboards use the value of `default`.
The rendered files look OK and I tried a couple on a live server and that works for me. I have one issue: `kubernetes-mixin/dashboards_out/k8s-resources-cluster.json` still contains the `Prometheus`  for the selector and I don't see any more mentions of `Prometheus` anywhere in code. How does that file get that value?

Use `default` as a picker value for datasource variable

---

dashboards/network-usage/cluster-total.libsonnet
dashboards/network-usage/namespace-by-pod.libsonnet
dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/network-usage/pod-total.libsonnet
dashboards/network-usage/workload-total.libsonnet

The reasoning behind this PR is in https://github.com/coreos/kube-prometheus/issues/305#issuecomment-554664859. TL;DR: Pie charts are bad.
In second commit I fixed some inconsistencies in legends where it showed entries only as "namespace" text. Replaced it with pod name or workload name (like in the second screenshot).
Effect of this PR can be seen in the attached screenshots:
/cc: @brancz @s-urbaniak

Replace piecharts with Bar plots

---

config.libsonnet

support metrics for dasd disk devices which are used by most IBM Z systems

config.libsonnet: add dasd devices for IBM Z systems

---

config.libsonnet

similar to #345. support metrics for dasd disk devices which are used by most IBM Z systems
This is needed in releases 0.3 and 0.2 so that it can be incorporated in the cluster monitoring operator for the current release and release-4.3 to fix https://bugzilla.redhat.com/show_bug.cgi?id=1794934
(cherry picked from commit aaaefb771c25f3e6f49a5303966675bde8039f66)

[release-0.2] config.libsonnet: add dasd devices for IBM Z systems

---

config.libsonnet

support metrics for dasd disk devices which are used by most IBM Z systems
This is needed in releases 0.3 and 0.2 so that it can be incorporated in the cluster monitoring operator for the current release and release-4.3 to fix https://bugzilla.redhat.com/show_bug.cgi?id=1794934
(cherry picked from commit aaaefb771c25f3e6f49a5303966675bde8039f66)

[release-0.3] config.libsonnet: add dasd devices for IBM Z systems

---

alerts/kubelet.libsonnet

This PR will stop users of `cluster-autoscaler` or other autoscaling features getting alerts when a node is shutdown by the autoscaler.
This should solve #300.

Added 2 minutes before firing KubeNodeUnreachable

---

alerts/resource_alerts.libsonnet

When using cluster autoscaler, it is common to have a deployment that keeps a few nodes "empty" - this is how you can achieve [over provisioning](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler). The CPU/memory overcommit alert should ignore those deployments because they there just to keep the node - and can be evicted any time a real pod need scheduling. I added a new property, `placeholdersNamespaceSelector` that can be set to ignore them.

ignore placeholder namespaces

---

alerts/kube_apiserver.libsonnet

#351  broke my prometheus rules:
```
level=error ts=2020-02-12T07:16:47.307Z caller=manager.go:832 component="rule manager" msg="loading groups failed" err="/etc/prometheus/rules/prometheus-k8s-rulefiles-0/monitoring-prometheus-k8s-rules.yaml: groupname: \"kube-apiserver-error\" is repeated in the same file"
```

Fix groupname is repeated in the same file error

---

alerts/kube_apiserver.libsonnet

This PR is adding two alerts. 
The first one `AggregatedAPIDown` will alert when an aggregated API server was down for at least 5 minutes. 
The second one `AggregatedAPIErrors` alerts when an aggregated server reported some errors. In general, errors like that might result in service unavailability including the whole system. When the number of errors is high it usually means that service was changing its availability too often (frequent `on/off`).

alerts when an aggregation API is down or it reports errors

---

alerts/kubelet.libsonnet
rules/kubelet.libsonnet
rules/rules.libsonnet
tests.yaml

Fire warning and critical alerts when the Kubelet's Pod Liecycle Event Generator (PLEG) interval metric exceeds configured durations.

Add alerts for long kubelet PLEG intervals

---

alerts/apps_alerts.libsonnet

We have some services (ie. Cortex ingesters) whose deployment takes a long time in a large clusters and cause the `KubeDeploymentReplicasMismatch` or `KubeStatefulSetReplicasMismatch` to trigger.
A solution we've found working for our use case is to change these alerts to not trigger until there's some progress during rolling updates. In this PR I'm proposing to upstream this change.

Do not alert mismatch replicas during rolling updates

---

alerts/kubelet.libsonnet

This is more for discussion, feel free not to merge :)
I had an issue with kubelet taking long time to spin up pods, turns out there was a cronjob which had created cronjob with 700 image pull back off jobs, which made kubelet slow down on pod creation for other things.
So in general I think maybe it's worthwhile to monitor pod start up latency

Add KubeletPodStartUpLatencyHigh alert

---

dashboards/network-usage/cluster-total.libsonnet
dashboards/network-usage/namespace-by-pod.libsonnet
dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/network-usage/pod-total.libsonnet
dashboards/network-usage/workload-total.libsonnet

The relative import path to the promgrafonnet.libsonnet was wrong here:
```
##[error]importing jsonnet: couldn't open import "../lib/promgrafonnet/promgrafonnet.libsonnet": no match locally or in the Jsonnet library paths
```
Turns out the imported objects aren't used.

Remove unused promgrafonnet import

---

alerts/kubelet.libsonnet

Some node has a capacity of 1 like AWS's Fargate and only exists while a pod is running on it.
We have to ignore this special node in the KubeletTooManyPods alert.

Fix KubeletTooManyPods on fargate nodes

---

dashboards/resources/workload.libsonnet

The `workload` has an incorrect check for `showMultiCluster` applied which makes it invisible unless applied.

Remove the showMultiCluster check for workload name

---

alerts/add-runbook-links.libsonnet

The `addRunbookURL` method overwrites this annotation on all of our alerts.  Adding a check to not add the rule if one already exists.

Preserve runbook urls

---

alerts/resource_alerts.libsonnet

Renaming duplicate alerts.
This could be prevented in future with https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/384

alerts: rename duplicate Kube*Overcommit alerts

---

alerts/kube_apiserver.libsonnet
config.libsonnet
dashboards/apiserver.libsonnet
jsonnetfile.json
rules/kube_apiserver.libsonnet

SIG Scalability has some documents around SLOs for the APIServer. The make a difference between mutating, what I called _write_ (with verbs `verb=~"POST|PUT|PATCH|DELETE"`), and non-streaming read-only API calls, what I called _read_ (with verbs  `verb=~"LIST|GET"`).
This PR adds recording rules for multi error burn rate alerts and some general rules that compute the availability of the APIServer. Next to that I also added some singlestat showing the overall availability of the APIServer, a graph with the remaining error budget. In the 2 rows below I've added the SLIs for reading and writing. It's basically a RED dashboard row with the availability for read and write at the beginning.
As a user of the project, the only real decision I need to make are:
1. For what time span do I want to …

Add APIServer SLOs based on community guidelines

---

alerts/apps_alerts.libsonnet

We have been seeing many false positives for 10 minute time range when
autoscaler was present in the clusters. This extends the time to 15
minutes as based on our observation that was enough time for the false
positives to be resolved.

alerts: Extend the for of KubeDaemonSetMisScheduled to 15 minutes

---

dashboards/apiserver.libsonnet
rules/kube_apiserver.libsonnet

After getting  a few reports (one for the previous implementation) I decided to split up the recording rule that calculates availability over 30d.
```
level=warn ts=2020-04-07T14:44:41.760Z caller=manager.go:525 component="rule manager" group=kube-apiserver.rules msg="Evaluating rule failed" rule="record: code:apiserver_request_total:increase30d\nexpr: sum by(code) (increase(apiserver_request_total{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[30d]))\nlabels:\n  verb: write\n" err="query processing would load too many samples into memory in query execution"
```
Instead of calculating `sum by (code) (increase(apiserver_request_total{job="apiserver",verb=~"POST|PUT|PATCH|DELETE"}[30d]))` directly, we now create the recording rule `code_verb:apiserver_request_total:increase30d` and then …

Add intermediate recording rule for APIServer availability

---

alerts/kubelet.libsonnet

Fixes https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/392

Fix KubeletPodStartUpLatencyHigh many-to-many matching not allowed

---

jsonnetfile.json

It's an old release, I know, but still used and installing using `jb v0.3` yields:
```
WARN: cannot link 'github.com/grafana/jsonnet-libs/grafana-builder' to 'vendor/grafana-builder', because package 'github.com/kausalco/public/grafana-builder' already uses that name. The absolute import still works
```

kausal/public -> grafana/jsonnet-libs for v0.1

---

dashboards/resources/node.libsonnet

I'd like to select multiple nodes to compare workloads across nodes. For example, GKE on preemptible nodes will restart or replace nodes quite often while workloads are fairly stable.

Allow selecting multiple nodes

---

alerts/kube_apiserver.libsonnet

REF: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/401

Remove AggregatedAPIDown alert from 0.4-release

---

alerts/kube_apiserver.libsonnet

Reverts kubernetes-monitoring/kubernetes-mixin#407
Kubernetes 1.18 has the fix for this alert, so 0.4 should include this alert. (RE: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/358#issuecomment-593328376)
@povilasv @lilic

Revert "Remove AggregatedAPIDown alert from 0.4-release"

---

dashboards/apiserver.libsonnet
rules/kube_apiserver.libsonnet

First, I've added a more explicit `code_verb:apiserver_request_total:increase30d` recording rule for which we now iterate over `for code in ['2..', '3..', '4..', '5..']` and `for verb in ['LIST', 'GET', 'POST', 'PUT', 'PATCH', 'DELETE']` evaluating these individual combinations on their own. This will add 24 more recording rules, but nicely split those up :)
The 3min evaluation interval has the nice side effect of really saving some CPU again (as reported by others resulting in higher usage, hi @smoke)
Additionally, I also had to fix the `scope=~"resource|"` for Kubernetes 1.18+, as the `scope="resource"` doesn't seem to exist anymore. 
---
The dashboard need some cleaning up and I put a bit time into it:
The biggest change here would be that both Read and Write SLI - Requests panels now …

Separate kube-apiserver-availability.rules into own group (w/ 3min interval)

---

alerts/kubelet.libsonnet

This is result of testing queries listed in comments in #300 on autoscaled cluster.
`for: 2m` is no longer necessary as autoscaler decision is taken into consideration during evaluation of alerting rule.
Fixes #300 
Different approach to #400

prevent KubeNodeUnreachable from firing when cluster is autoscaled down

---

alerts/apps_alerts.libsonnet

Currently this alarm fires when a pod was `CrashLooping` during the last 5 minutes and not like mentioned in the message in the last 5 minutes.
Signed-off-by: Guus van Weelden <guus.vanweelden@moia.io>

adjust time window for `KubePodCrashLooping` alert

---

dashboards/resources/cluster.libsonnet

Template was added twice in this dashboard when `showMultiCluster: true` was set.

Double Cluster template in cluster dashboard with multi cluster enabled.

---

alerts/kube_apiserver.libsonnet

KubeAPIErrorBudgetBurn alerts can generate duplicate samples which would cause warnings in the Prometheus logs. For a given severity label (e.g. warning or critical), there are 2 alert rules for different burn rates but their labels sets are identical.
To avoid this situation, this change adds ~~a 'factor' label~~ 'short' and 'long' labels to differentiate between alerting rules.
Other options I have evaluated:
* ~~using the short and long interval of the alert.~~
* using the factor value of the alert.
* using the `for` clause.
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1832819

Add 'factor' label to KubeAPIErrorBudgetBurn alerts

---

dashboards/resources/cluster.libsonnet

`mixin_pod_workload` doesn't include static pods. Using `kube_pod_owner` instead renders correct numbers.
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1836048

dashboards/resources: include static pods for overall pod count

---

alerts/kube_apiserver.libsonnet

Right now when alert fires, value which is sent doesn't have much meaning for the operator. It would be beneficial to send value from `cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{quantile="0.99"` instead.
closes #434
/cc @rira12621

alerts: reorder query for better alert message

---

config.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet

fixes #429 
I went through all the `kubernetes-mixin` dashboard that had `No Data` / `N/A` errors and applied an interval to fix it.

fix panels with no data due to no minimal interval

---

alerts/apps_alerts.libsonnet

I've noticed the `KubeStatefulSetUpdateNotRolledOut` fires every time a statefulset rollout takes more than 15m. In this PR I'm proposing to fix it using the same technique we used in the `KubeStatefulSetReplicasMismatch` and having the alert not alerting if the statefulset rollout is progressing.

Do not fire KubeStatefulSetUpdateNotRolledOut while a statefulset is rolling out

---

dashboards/defaults.libsonnet

Various tools in the SRE space use UTC as the default to make it
effortless during incidents to not have to calculate between timezones.
Just an example, both Prometheus and Thanos default to this behavior as
well. People can still override this in downstream usage, but I think we
should be promoting best practices.
@povilasv @metalmatze @s-urbaniak @lilic

dashboards: Default dashboards to UTC

---

dashboards/apiserver.libsonnet

Make it clear that a reference to SLO in the dashboards does not
imply a contractual SLA.

dashboards: add notice that SLO does not imply SLA

---

alerts/apps_alerts.libsonnet
runbook.md

Alert is redundant with KubeJobCompletion, both provide the same information and fire in the same situation.
From my observations, `KubeJobCompletion` is better due to relying on more stable metrics. `KubeCronJobRunning` can cause false positives when kube-state-metrics doesn't properly update `kube_cronjob_next_schedule_time` metric (which in itself is kind of predicion type of metric).

remove KubeCronJobRunning alert

---

README.md

Added rough compatibility guidelines based on our use in kube-prometheus and openshift. It's a start to at least not forget what branch goes with with version, but we should be adding better testing!
cc @povilasv @brancz

README.md: Update release branches compatibility matrix

---

alerts/kube_apiserver.libsonnet
runbook.md

Especially KubeAPILatencyHigh has been very flaky for a lot of people
and has since been replaced with the more advanced
KubeAPIErrorBudgetBurn alert, that only warns or pages if availability
overall cannot be guaranteed anymore. The same for KubeAPIErrorsHigh.
/cc @brancz @lilic @s-urbaniak @paulfantom @csmarchbanks @povilasv @tomwilkie

Delete KubeAPILatencyHigh and KubeAPIErrorsHigh

---

rules/kube_apiserver.libsonnet

As discussed in #416, this allows graceful degradation if the
corresponding time series do not exist (as it is the case on some
versions of the API server or perhaps even on certain hosted K8s
offerings).

Add `or vector(0)` to selected rules

---

alerts/kubelet.libsonnet
tests.yaml

Currently, `kubelet_running_pod_count` includes `Completed` pods, which
is incorrect from the point of `KubeTooManyPods` alert. Since every pod needs to have `container_memory_rss` exposed, we can leverage it to find the actual number
of pods running on a node.
Workaround fix #442

alerts: do not include completed pods in KubeTooManyPods alert

---

dashboards/apiserver.libsonnet

The dashboard already had a template for multiCluster support but only
some of the queries were using the clusterLabel variable. Unfortunately
the singlestat panels did not work as expected because the clusterLabel
was not being used so multiple values were being returned if multiple
clusters are discoverable. As such, lets also add the clusterLabel
variable to the to the rest of the queries.

dashboards: Make the API dashboard cluster aware

---

dashboards/resources/pod.libsonnet

Currently, Kubelet cAdvisor exports metrics for the parent cgroup as
well as for each container. This leads to having "duplicate metrics" and
espacially lead to strange or wrong visualisations.
Filtering by `container!=""` exclude metrics from the parent cgroup.
This patch avoids having two time-series in the CPU Throttling panel.
Related to #136 
Metrics from `container="POD"` are already removed from the current panel.
Before the patch:
After the patch:

dashboards/pod: Fix usage of duplicate cAdvisor time-series

---

dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/network-usage/workload-total.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet
rules/apps.libsonnet
tests.yaml

The recording rule `mixin_pod_workload` doesn't match recording rule best practices (https://prometheus.io/docs/practices/rules/#naming-and-aggregation). Open to other changes to the name from maintainers, but the aggregation level seemed like the obvious low hanging fruit change.
@brancz 
cc @tomwilkie 
Signed-off-by: Callum Styan <callumstyan@gmail.com>

update mixin workload recording rule name 

---

alerts/kubelet.libsonnet

For KubeNodeUnreachable, this can be ignored too.
Origin:
https://github.com/aws/aws-node-termination-handler/blob/f5f8766609022dd8c2df18367089205e3a8ce92e/pkg/node/node.go#L48-L49
Refs: #459, #460

ignore aws-node-termination-handler/spot-itn

---

dashboards/resources/namespace.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet

We get two values scraped from both the default `/metrics/cadvisor` and `/metrics/resource/v1alpha1` which are then summed together and causing double representation of memory usage.
Excluded image from `container_memory_working_set_bytes` except for the usage of the `node_namespace_pod_container:container_memory_working_set_bytes` rule which excludes [image by default](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/rules/apps.libsonnet#L34).
Fixes #458 #136 
Before:
After:

Exclude v1alpha1 metrics from container memory metrics

---

README.md
alerts/resource_alerts.libsonnet
runbook.md

alerts/resource_alerts.libsonnet, runbook.md: Reduce KubeQuotaExceeded severity and adjust threshold
This PR is needed in order for those changes to land in and older version of [cluster-monitoring-operator](github.com/openshift/cluster-monitoring-operator)

Cherry-pick pull request #450 from RiRa12621/master

---

dashboards/controller-manager.libsonnet
dashboards/kubelet.libsonnet
dashboards/proxy.libsonnet
dashboards/scheduler.libsonnet

- `rest_client_request_latency_seconds` was deprecated since Kube v1.14 and has been [turned off since v1.17](https://github.com/kubernetes/kubernetes/pull/83836). replaced it with `rest_client_request_duration_seconds`

replace deprecated metric rest_client_request_latency_seconds

---

alerts/kube_apiserver.libsonnet

In the current form, the alert fires if
`aggregator_unavailable_apiservice` is 1 in only a single scrape. As
hinted in the message, that's probably not the intention of the alert.
Rather than requiren 5m complete downtime, however, I think it's best
to measure the availability over the last 5m and alert on that, still
guarded by a `for: 5m` clause to avoid firing if the metrics just
starts to come in for a new instance and happens to start with a
failure.

Fix AggregatedAPIDown alert

---

dashboards/apiserver.libsonnet

- revert back span length changes for workqueue metrics panels from https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/403
with span=4, workQueueLatency panel doesn't show the graph properly, legend data takes up the entire panel, due to the legend_show=true:
cc @metalmatze since he authored the original change.

change back span length for some panels in apiserver dashboard

---

dashboards/apiserver.libsonnet

Fixes #379 
these metrics are not available since Kube v1.16 release, that is when Kubernetes removed support for etcd2 storage backend.

remove deprecated etcd2 api storage metrics from apiserver dashboard

---

alerts/apps_alerts.libsonnet

In most cases when KubeJobFailed is triggered, KubeJobCompletion follows and can cause alert fatigue. To solve this I propose to increase `for` statement in KubeJobCompletion. This way failing cron jobs would already be covered by `KubeJobFailed` and alerting on jobs entering infinite loop would be done after an extended period.
Additionally, it solves a problem of unnecessary alerting on longer running jobs (like backups).
Another approach would be to completely remove `KubeJobCompletion` alert or provide a customizable timeout.

alerts: prevent KubeJobCompletion and KubeJobFailed firing at the same time

---

alerts/apps_alerts.libsonnet

backport this change in order to allow it to be backported to older openshift versions

alerts: prevent firing KubeJobCompletion and KubeJobFailed at the same time

---

alerts/apps_alerts.libsonnet

https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/473 was introducing a change to the timeframe for which a jobs doesn't complete.
This PR adjusts the error message accordingly

alerts: adjust error message accrodingly to recent change

---

alerts/apps_alerts.libsonnet
tests.yaml

Technically we also want to take observed generation into account, but there is currently no metric for this in kube-state-metrics and we'll want to wait a couple of releases after it's released to make use of that metric (see https://github.com/kubernetes/kube-state-metrics/issues/1176).
Once observed generation is available, we can also add:
```
kube_daemonset_metadata_generation{%(prefixedNamespaceSelector)s%(kubeStateMetricsSelector)s}                                                                                                                                                                  
==
kube_daemonset_status_observed_generation{%(prefixedNamespaceSelector)s%(kubeStateMetricsSelector)s}
```
In the beginning, but this is already much improved. And I'll open an issue after …

alerts: Improve DaemonSet rollout alert taking progress into account

---

alerts/kube_apiserver.libsonnet

With the current setting, very few individual scrapes reporting the
API as unavailable can trigger the alert. Even with a scrape interval
of only 15s, the 5m range contains only 20 scrapes, and three scrapes
reporting the API as down will trigger the alert. With 30s scrape
interval, two scrapes will trigger. With 60s, even a single scrape is
enough.
With the suggested change, two scrape are needed with 60s interval,
four scrapes with 30s, and seven with 15s. Note that a consistently
down API will still trigger the alert after only 2m (plus the 5m from
the `for` clause). Response time is therefore not a problem. However,
if the availability is hovering around 90% all the time, the alert
will never fire. I'm assuming for now that that's not a problem to
alert on anyway, but it is, we need a …

Make `AggregatedAPIDown` even less noisy

---

alerts/kubelet.libsonnet

This brings it inline with KubeNodeNotReady
This alert has a low signal-to-noise ratio for many of our customers. We have seen it fire during short periods of high IOPS which cause the kubelet to become unreachable. The kubelet recovers, but the customers are panicked by the alert. KubeNodeUnreachable and KubeNodeNotReady are similar in severity and in how they might be handled, so it seems reasonable to me that they have similar alerting times.

Wait 15 minutes before alerting on KubeNodeUnreachable

---

alerts/kubelet.libsonnet
tests.yaml

This change adds alerts to monitor expirations of the kubelet's client
and server certificates as well as failures to renew the certificates.

Add alerts for Kubelet client/server certificates

---

dashboards/resources/pod.libsonnet

Within the _Kubernetes / Compute Resources / Pod_ dashboard, the _clusterLabel_ selector is omitted in the denominator of two columns of the "Memory Quota" table, while it **is** present in the numerator:
- Memory Requests %
- Memory Limits %
This leads to incorrect reporting of these metrics in the case of identical Pod names over multiple clusters (e.g. when using StatefulSets).

add missing clusterLabel to expression denominator

---

alerts/resource_alerts.libsonnet
runbook.md

Add alert for KubeQuotaExceeded only when the quota exceeded and split the condition where 
the quota is reached `= 1` and quota is exceeded `> 1`.
As the quota being fully used should totally be ok. And no one will complain about this. 
So just inform the user in case they see any issue based on that. Like the application failed to be created.
And when the quota is over-committed, administrator or user should be alerted and take action on that.
cc @RiRa12621 @NautiluX

Split the alerts for quota usage reached and exceeded

---

dashboards/kubelet.libsonnet

* Kubelet v1.19 CHANGELOG lists two metrics renames
* `kubelet_running_pod_count` --> `kubelet_running_pods`
* `kubelet_running_container_count` --> `kubelet_running_containers`
Related: https://github.com/kubernetes/kubernetes/pull/92407

Rename Kubelet pod/container counts for Kubernetes v1.19

---

dashboards/resources/multi-cluster.libsonnet

* In multi-cluster dashboard, memory requests are by cluster label, not by namespace

Fix multi-cluster memory requests panel title

---

alerts/apps_alerts.libsonnet

Backporting #414 to fix the issue on 1.18 Kubernetes environments.
According to [support matrix](https://github.com/kubernetes-monitoring/kubernetes-mixin#releases), `release-0.4` is the branch responsible for k8s 1.18).

Backport #414

---

dashboards/windows.libsonnet
rules/windows.libsonnet

Wmi_exporter has been renamed to windows_exporter and all the metrics prefix from wmi_ has been changed to windows_
This PR fix by updating the metrics prefixes.
https://github.com/prometheus-community/windows_exporter/releases/tag/v0.13.0

Renamed wmi_ metrics to windows_ for Windows_exporter

---

dashboards/apiserver.libsonnet
dashboards/controller-manager.libsonnet
dashboards/kubelet.libsonnet
dashboards/network-usage/cluster-total.libsonnet
dashboards/network-usage/namespace-by-pod.libsonnet
dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/network-usage/pod-total.libsonnet
dashboards/network-usage/workload-total.libsonnet
dashboards/persistentvolumesusage.libsonnet
dashboards/proxy.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/resources/multi-cluster.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/node.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet
dashboards/scheduler.libsonnet
dashboards/statefulset.libsonnet
dashboards/windows.libsonnet
jsonnetfile.json
lib/promgrafonnet/gauge.libsonnet
lib/promgrafonnet/numbersinglestat.libsonnet

In an effort to streamline all jsonnet imports to use absolute import paths in various projects, as they are easier to grasp, we need to change them here too.
Nothing really changes as previously the old folder used were just symlinks from `vendor/grafonnet` => `vendor/github.com/grafana/grafonnet-lib/grafonnet/` anyway. :)
Hopefully, it'll be very obvious going forward where dependencies live that we import.

Start using absolute jsonnet imports

---

alerts/apps_alerts.libsonnet
tests.yaml

For some it is unclear how to proceed when this alert fires and mostly how to clear it even after failed job was investigated.
/cc @wking

alerts: be explicit how to proceed when KubeJobFailed is firing

---

dashboards/resources/cluster.libsonnet
dashboards/resources/namespace.libsonnet

Fix a couple of network TX queries on resources dashboards that were using `receive` metric instead of `transmit` metric.

Fix TX network queries resources dashboards

---

alerts/apps_alerts.libsonnet

When an HPA desired replicas count is outside of the specified min and max replicas count, an alert is firing. This can be annoying, for example, when the desired count is 0 but the min replicas count is 1.

alerts: prevent hpa false positive alerts

---

dashboards/statefulset.libsonnet

Same as my previous PR (#456), partial fix for #136.
Currently, Kubelet cAdvisor exports metrics for the parent cgroup as
well as for each container. This leads to having "duplicate metrics" and
especially lead to strange or wrong visualizations.
Filtering by `container!=""` exclude metrics from the parent cgroup.
This patch avoids having two time-series in the CPU Throttling panel.
Unlike my previous PR, `container="POD"` is not removed from these panels but its value is always 0 AFAIK.
Sorry for the lack of screenshot.
**Before the PR:** values for CPU usage and Memory usage in the Statefulset dashboard are twice the real usage
**After the PR:** values match real usage
**Note:** I also added a missing cadvisorSelector for `container_network_receive_bytes_total`

dashboards/statefulset: Fix usage of duplicate cAdvisor time-series

---

README.md
config.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/resources/multi-cluster.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet

as Described in https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/ 
when using `$__interval` for intervals in rate like functions depending on the actual scrape interval of the target, the range selected in the time picker and the `min interval` in the panel grafana might not be able to display any data in the panels.
In the current dashboards the `min interval` is unset and is not configurable.
Starting with Grafana 7.2 a new variable called `$__rate_interval` is available to let grafana select the right interval for rate like functions addressing also the minimum interval issue.
With this PR a new `$_config.grafana72` boolean flag is added, default to false , to select which type of interval variable to use in the rendered …

Add support for GRAFANA72 $__rate_interval using a boolean flag

---

rules/apps.libsonnet
rules/kube_apiserver.libsonnet
rules/node.libsonnet

As in title.
Additionally, all rules from [kube_scheduler.libsonnet](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/rules/kube_scheduler.libsonnet) are unused, should we remove them?

Remove recording rules which are used in neither dashboards nor alerts

---

README.md

Note: technically we do plan to use release-0.6 in k8s 1.20, so tentatively setting `1.19+` in the compatibility matrix but since it is not released yet.
Please let me know if this ok from the maintainers perspective. We can also bump to `1.20`.
Signed-off-by: Sergiusz Urbaniak <sergiusz.urbaniak@gmail.com>

README: cut release-0.6

---

dashboards/kubelet.libsonnet

Those metric names only work on k8s 1.19+ , they were changed in https://github.com/kubernetes/kubernetes/pull/92407
With the query changed this way the widget will work on both < 1.19 and >=1.19 transparently.

Make kubelet dashboard backward compatible

---

alerts/kube_apiserver.libsonnet
dashboards/network-usage/cluster-total.libsonnet
dashboards/network-usage/namespace-by-pod.libsonnet
dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/network-usage/pod-total.libsonnet
dashboards/network-usage/workload-total.libsonnet

This alert has fired routinely for different cloud providers. Without
having done exacts science and having investigated the various SLAs
(should they actually exist for the API), I have concluded that the
expectations of this alerts are too high. The relatively short hiccups
never caused any noticable issues. So this is doubling the time to
average over.
I have also simplified the wording in the details.
`make fmt` created a bunch of reformattings that are unrelated to this
change. I guess that's because of a new version of jsonnet. I can
remove them from this commit if that's undesired here.

Make AggregatedAPIErrors less noisy

---

dashboards/persistentvolumesusage.libsonnet

Queries for grafana gauge panel need to result in only one series. However, they won't if the pod associated with PV is moved to other node. This change resolves that issue by discarding `node` and `instance` labels.

dashboards: remove node and instance labels from PV queries

---

OWNERS

As discussed in Kubernetes Slack, I kindly suggest to add @paulfantom to the list of maintainers (approvers and reviewers) for this repository :-)
This also adds @povilasv to the OWNERS file as his alias was missing.
cc @brancz @povilasv @tomwilkie @csmarchbanks @metalmatze @paulfantom 
side note: I do not have permissions to add @paulfantom to the github team member list, so I kindly ask an owner to do this. Thank you!

OWNERS: add povilasv and paulfantom

---

runbook.md

This PR aligns `runbook.md` with the severity changes of cause based alert to `warning` in #402 
The only alert that was not present in `runbook.md` is `KubeStatefulSetUpdateNotRolledOut`. How should I proceed to add that to `runbook.md`?

Change severity of cause based alerts to warning

---

runbook.md

Fixes a mistake in the runbook where KubeCPUOvercommit/KubeMemOvercommit showed up twice and KubeCPUQuotaOvercommit/KubeMemQuotaOvercommit didn't show up
Got me confused for a minute before I checked the Prometheus rules to see it was misspelled in the documentation
Pictured below, the real name of the alert
Haven't found any repo specific instructions on how to contribute and seeing as its just a change in the documentation, this should be fine?

Fixes the alert names in the runbook for KubeCPUQuotaOvercommit/KubeMemQuotaOvercommit

---

alerts/kube_apiserver.libsonnet
runbook.md
tests.yaml

This PR adds a new alert that fires when the number of inbound requests 
terminated by the APIServer exceeds 30% of the total inbound requests. 
Requests can be terminated due to timeout or throttling caused by the 
[API Priority and Fairness ](https://v1-19.docs.kubernetes.io/docs/concepts/cluster-administration/flow-control) policies.
This alert helps platform owners to surface request failures such as those
described in [BZ 1905235](https://bugzilla.redhat.com/show_bug.cgi?id=1905235).
The alert condition is defined as the ratio of the total terminated requests to
the total requests, using the `apiserver_request_terminations_total` and
`apiserver_request_total` metrics.The total inbound request is determined 
by the summation of the two metrics because the `apiserver_request_total` …

Add New Alert to notify on APIServer Terminated Request

---

rules/kube_apiserver.libsonnet

This PR applies the following suggestion from @beorn7 https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/411#issuecomment-641238064, to fix Prometheus evaluation errors reporting that the `code_verb:apiserver_request_total:increase30d` recording rule can't be evaluated because it's loading too many samples.
After experimenting with the suggested recording rule https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/411#issuecomment-748167633, it was concluded that the new lightweight approach is precise enough to replace the existing one.
Fixes #411

Fix `code_verb:apiserver_request_total:increase30d` loading too many samples

---

dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet

This PR adds cluster labels to queries in pod.libsonnet and workload-namespace.libsonnet to allow multi cluster setups

feat: add cluster labels to pod and workload-namespace libsonnet

---

alerts/apps_alerts.libsonnet

During deployments and statefulsets rolling updates we frequently experience the alerts `KubeDeploymentReplicasMismatch` and `KubeStatefulSetReplicasMismatch` firing because some of our applications do stuff on shutdown / startup (eg. transfer state, replay WAL, ..) which slow down the rollout. 
What's the sentiment if we increase the tolerance on changes from 5m to 10m?

Increased replicas mismatch alert tolerance

---

alerts/system_alerts.libsonnet

This has been renamed in v1.19: https://github.com/kubernetes/kubernetes/pull/91805
Let me know if this needs/should be done in a backward compatible way instead.

Rename gitVersion to git_version

---

dashboards/windows.libsonnet

When rendered this dashboard panel had a `"datasource": null` and was using `"queryType": "randomWalk"` which was regenerating fake data each refresh. 
It is now showing the correct data:

Set the Windows Disk IO Utilisation dashboards datasource

---

rules/windows.libsonnet

This rule was using the wrong metric names for calculation and was return nothing.  According to the `net` [collector](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.net.md) for the windows_exporter the values are:
```
windows_net_packets_received_discarded_total
windows_net_packets_outbound_discarded_total
```

Use correct metric names for windows network traffic

---

dashboards/resources/cluster.libsonnet

Currently `CPU Requests Commitment`  & `CPU Quota -> CPU Requests` in the `Kubernetes/Compute Resources / Cluster` include pods that are no longer running.

Changes CPU request total to sum running/pending pods only

---

dashboards/windows.libsonnet
rules/windows.libsonnet

When running the windows dashboard I found that the rules where failing and no data was being shown on the graphana dashboards.  This PR updates the windows metric to be uniquely named and not overlap with the metric exported by [windows_exporter](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.container.md).
```
record:windows_container_available
expr:windows_container_available{job="windows-exporter"} * on(container_id) group_left(container, pod, namespace) max by(container, container_id, pod, namespace) (kube_pod_container_info{job="kube-state-metrics"})
```
and
```
found duplicate series for the match group {} on the right hand-side of the operation: [{__name__="windows_container_available", …
```

Use non-overlapping rule name

---

rules/node.libsonnet
tests.yaml

There's an edge case triggering many-to-many errors for the
node:node_num_cpu:sum rule. After a Prometheus pod with persistent
storage is restarted, there is a short window of time (e.g. 5m) during
which 2 timeseries for the "node_namespace_pod:kube_pod_info:" metric
are returned for the same ("namespace", "pod") labels but with different
"node" label values. This is because Prometheus didn't mark the "old"
series as stale on shutdown.
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1908655

rules/node.libsonnet: fix many-to-many errors for node:node_num_cpu:sum

---

rules/apps.libsonnet

Problem:
When we use MultiCluster flag, in the "cluster" dashboard (in resource), some boxes does not properly show datas.
These two faulty box are feeded by record rules:
`sum﻿(﻿namespace:kube_pod_container_resource_requests_cpu_cores:sum﻿{﻿cluster﻿=﻿"$cluster"﻿}﻿)﻿ / ﻿sum﻿(﻿kube_node_status_allocatable_cpu_cores﻿{﻿cluster﻿=﻿"$cluster"﻿}﻿)`
```
namespace:kube_pod_container_resource_requests_memory_bytes
namespace:kube_pod_container_resource_requests_cpu_cores
g.statPanel('sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum{%(clusterLabel)s="$cluster"}) / sum(kube_node_status_allocatable_memory_bytes{%(clusterLabel)s="$cluster"})' % $._config)
g.statPanel('sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum{%(clusterLabel)s="$cluster"}) / …
```

repair empty box when using multicluster

---

dashboards/resources/workload-namespace.libsonnet

<![2021-03-12_15-45](https://user-images.githubusercontent.com/58891894/110959461-01740300-834e-11eb-9e62-25ff57326edc.png)
With multicluster=true, the logic of selecting the workload before the cluster looks strange (??), all dashboards start by datasource > cluster which look logics.
This PR standardize the dashboard by giving the same order of variables (as others)

fix wrong logic between dashs

---

dashboards/resources/pod.libsonnet
rules/apps.libsonnet

Pause container is counted towards overall pod resource consumption and shouldn't be excluded.
Related to https://github.com/prometheus-operator/kube-prometheus/pull/1037

dashboards,rules: include pause container in resource calculation

---

dashboards/resources/cluster.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet

This reverts fc8ed7032fee08cd25dfda4257ae48146f5be347, puts all network panels that come in a receive and a transmit flavor into the same row and renames the rows according to the panel contained.
Fixes: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/570
The original fix of adding `gridPos` to the `addPanel` calls doesn't work for now as the `grafana.libsonnet` from github.com/grafana/jsonnet-libs/grafana-builder/ used in these dashboards doesn't support it.

dashboards: revert single row for network panels and condense/rename rows

---

alerts/kubelet.libsonnet
alerts/resource_alerts.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/resources/multi-cluster.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/node.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet
rules/apps.libsonnet
rules/windows.libsonnet
tests.yaml

KSM v2 renames and drops some metrics which are used in this mixin. ~This PR is an attempt to make mixin compatible with KSM v1 and v2 at the same time.~
More info about what needs to be adapted is available in KSM changelog: https://github.com/kubernetes/kube-state-metrics/blob/master/CHANGELOG.md#v200-alpha--2020-09-16

Kube-state-metrics v2 compatibility

---

alerts/kube_apiserver.libsonnet

In Kubernetes 1.19, the aggregator_unavailable_apiservice_count metric
was renamed to aggregator_unavailable_apiservice_total. Thus, the
AggregatedAPIErrors alert needs to be updated to use the new metric.
cf. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#other-cleanup-or-flake-5

Update AggregatedAPIErrors after Kubernetes 1.19 changes

---

dashboards/resources/cluster.libsonnet
dashboards/resources/multi-cluster.libsonnet

This PR removes the `%(clusterLabel)s="$cluster"` label matcher from the multi-cluster dashboard.
This matcher does not make sense to include in the context of the headlines section, since we are aggregating across all clusters in the context of those queries (and not _by_ cluster). The queries themselves were also broken due to missing a `}` after the `$cluster` label matchers, and have also been fixed.
Finally, a typo has been fixed in the 'Memory Utilisation' section of the cluster dashboard.

Fix dashboard regressions in 'Multi-Cluster' and 'Cluster'

---

dashboards/network-usage/cluster-total.libsonnet
dashboards/network-usage/namespace-by-pod.libsonnet
dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/network-usage/pod-total.libsonnet
dashboards/network-usage/workload-total.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/node.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet

Change the default variable refresh behavior from "On Dashboard Reload" to "On Time Range Change" on Grafana dashboards.
That is quite useful when navigating to old data, avoiding refresh the dashboards every new time range change.
https://github.com/openshift/cluster-monitoring-operator/pull/1097

chore/dash-var-refresh: change default refresh to 2(time range)

---

alerts/resource_alerts.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/resources/multi-cluster.libsonnet
rules/windows.libsonnet

There are still places where the old kube-state-metrics are used, e.g. Compute Resources / Cluster dashboard:
This Pull Request updates:
- `kube_pod_container_resource_requests_cpu_cores` -> `kube_pod_container_resource_requests{resource="cpu"}`
- `kube_pod_container_resource_requests_memory_bytes` -> `kube_pod_container_resource_requests{resource="memory"}`
- `namespace:kube_pod_container_resource_requests_cpu_cores:sum` -> `namespace_cpu:kube_pod_container_resource_requests:sum`
- `namespace:kube_pod_container_resource_requests_memory_bytes:sum` -> `namespace_memory:kube_pod_container_resource_requests:sum`
All of the above are exported with v2.0.0-rc.1

Fix kube_pod_container_resource metric name

---

alerts/apps_alerts.libsonnet

added missing selectors for kube_hpa_status_current_replicas

Fix for Alert KubeHpaReplicasMismatch

---

dashboards/resources/namespace.libsonnet

Add the `%(clusterLabel)s="$cluster"` label matcher to a few expressions on the namespace dashboard. 
Some panel queries show inaccurate calculations if your dataset contains metrics from multiple clusters that have namespaces with the same names (i.e. if they all have a `monitoring` namespace).
This PR fixes the above issue by specifying the `%(clusterLabel)s="$cluster"` label matcher in the relevant expressions.

fix(dashboards/namespace): add cluster label matcher to queries

---

dashboards/resources/cluster.libsonnet

This fixes the cluster memory utilization panel in the `Kubernetes / Compute Resources / Cluster` dashboard .
Before:     
After:

fix(dashboard): fix cluster memory utilization in cluster dashboard

---

alerts/resource_alerts.libsonnet

The alerts in question fire if resources are overcommited such that a
node failure could no longer be tolerated. In single node clusters this
alert is not applicable.
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

alerts/resource_alerts: don't alert resource overcommit on single node setups

---

dashboards/resources/cluster.libsonnet

After upgrade, the `Memory Utilisation` in `Compute Resource / Cluster` dashabord is unavaliable. 
After this edit, this problem can be fixed

Compute-resources/cluster: Delete resource label in Memory Utilisation

---

dashboards/resources/pod.libsonnet

In the Memory Usage panel the requests and limits query specified the
cpu resource. Seems like this was overlooked in the move to
kube-state-metrics v2.
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

Kubernetes/Compute Resources/Pod: Fix resource label

---

dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet

Seems the value is changed to cpu in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/534 while the replacement mechanism remains unchange.
Similliar pr: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/590

Use cpu instead of cpu_cores in cpuRequestsQuerys

---

README.md

I added information about kube-state-metrics dependency. After this is merged I would like to proceed with cutting the new release branch.

Cut release-0.8 branch

---

dashboards/kubelet.libsonnet

Kubelet is exposing data on at least 4 different URIs. This leads to duplication of `up` metrics and causes incorrect sum presented in the dashboard.

dashboards: fix number of kubelets being up

---

dashboards/resources/pod.libsonnet

This adds "Working Set" (WSS) to "Memory Usage" widget.
The "Memory Usage" titles should be properly labeled to indicate that they are "Working Set" (WSS), differencing and qualifying them from the RSS, Cache and Swap titles and data.

dashboards:  add "WSS" to the memory_usage widget label in grafana

---

dashboards/kubelet.libsonnet

This is a follow-up to #597 
Let's not use `up` to determine the number of kubelets as this is error-prone and heavily depends on the user setting correct `kubeletSelector`. Instead, we can get the same result using `kubelet_node_name` which doesn't require setting `kubeletSelector` to a specific value.
I also changed panel name to better align with query.
/cc @ravilr @brancz

dashboards: do not use `up` to count number of kubelets

---

dashboards/pods.libsonnet
dashboards/resources.libsonnet

I was getting odd results when upgrading prometheus-operator on a 1.16 cluster. I was unable to cherry-pick this due to other changes between release-0.3 and release-0.4.
Original PR https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/463 this was backported from.

Backport PR#463 to release-0.3 Exclude v1alpha1 metrics from container memory metrics

---

dashboards/persistentvolumesusage.libsonnet

When ReadWriteMany PVCs are mounted on multiple pods, duplicate timeseries are generated with identical values, resulting in incorrect graphs and broken gauges.

Pick single timeseries when graphing ReadWriteMany PVCs

---

dashboards/kubelet.libsonnet

Singlestat panels are deprecated. 
Statpanels do not support spans so I changed all panels to use gridPos (had issues aligning panels when only statpanels made use of gridPos).
Change reducer function to `lastNotNull` to fetch the last value and not the min one.
Should not change any dashboard UI except the singlestat->statpanel change.

dashboard/kubelet: Migrate to statPanel

---

alerts/apps_alerts.libsonnet

Hello,
Following the PR #531 , the time multiplier was not changed correctly.
Hence currently:
```
rate(kube_pod_container_status_restarts_total{..}[10m]) * 60 * 5
```
give us the number of restart per 5 minutes and not 10 minutes as the message annotation is saying..
This quick fix set it to be the number per 10 minutes.
Note: the PromQL could also be replaced with
```
increase(kube_pod_container_status_restarts_total{..}[10m])
```
which is equivalent and maybe more readable ?

Fix rate time for PodCrashLoopbackoff alert

---

alerts/apps_alerts.libsonnet

**What this PR does / why we need it:**
Support `kube-state-metrics` v2.0.0+
**Which issue(s) this PR fixes :**
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/621

Rename hpa metrics to support kube-state-metrics v2.0.0+

---

alerts/apps_alerts.libsonnet

**What this PR does / why we need it:**
Support `kube-state-metrics` v2.0.0+
**Which issue(s) this PR fixes :**
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/621

release-0.8 - update HPA metrics, support kube-state-metrics v2.0.0+

---

dashboards/resources/multi-cluster.libsonnet

Right now query for memory consumption in multi-cluster dashboard mixes node memory usage with kube allocatable memory. This can lead to negative values if there are other applications running outside of the cluster, but on nodes. Plus kubelet has memory reservation which is not counted towards allocatable memory for the cluster.
It might be good to expand this "headline" row and add `Pod CPU usage` as well as `Pod Memory usage`. This would give a clear distinction of how much memory is used in a cluster and how much is used by the nodes in total. If there is a need for it, I'll open an issue and possibly later - PR.

dashboards/resources: use one datasource for calculating memory consumption

---

alerts/apps_alerts.libsonnet

If a pod is running the alert should stop firing. This should improve recovery from the alert condition and prevent false-positives.

alerts: improve recovery for KubePodCrashLooping alert

---

alerts/storage_alerts.libsonnet
tests.yaml

After [1] kubelet metrics `kubelet_volume_stats_available_bytes` and `kubelet_volume_stats_used_bytes` are set to 0 for all block PVC mounts. This causes the `KubePersistentVolumeFillingUp` alert to be fired immediately.
Block volume mount stats can't really carry the `kubelet_volume_stats_used_bytes` because it is a raw storage device, not a file system. It is upto the workloads to deal with raw devices.
This PR fixes the alert expression by testing `kubelet_volume_stats_used_bytes > 0` which prevents alert for block volume mounts.
[1] https://github.com/kubernetes/kubernetes/commit/b997e0e4d6ccbead435a47d6ac75b0db3d17252f

fix: KubePersistentVolumeFillingUp - false alert fires for PVCs with volumeMode as block

---

alerts/apps_alerts.libsonnet

label.hpa is depreicated and should now be label.horizontalpodautoscaler
From alerts in slack. Should be HPA Default/*NAME*... image
Labels from alertmanager

Update depricated label hpa to horizontalpodautoscaler

---

alerts/apps_alerts.libsonnet
tests.yaml

Crashlooping containers are in `waiting` phase, which we can use for the alert.
This is a follow-up to #617 which wasn't sufficiently tested and introduced a bug that rendered alert useless. (Thanks @adinhodovic for reporting!)
I also added here a test case for the alert.
Below is a screenshot of a query when a crash-looping container is present.

Improve KubePodCrashLooping and add unit test for it

---

rules/kube_apiserver.libsonnet

This PR reduces the size of some rule groups (specifically the [apiserver rule groups](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/rules/kube_apiserver.libsonnet)), taking advantage of parallel execution of rule groups (with sequential execution within a group).
Also, in the `kube-apiserver-availability` group, the `apiserver_request:availability30d` rules reference the `code:apiserver_request_total:increase30d` metrics which are defined later in the group. If I understand correctly, since rules within a group are evaluated sequentially, the dependency rules should be defined first. This PR also fixes this.
The net change is a no-op with respect to recording rule metrics, and simply reorganizes the existing defined rules into smaller groups. I tried to keep the …

Reduce size of apiserver rule groups

---

alerts/alerts.libsonnet
alerts/kube_apiserver.libsonnet
alerts/utils.libsonnet
dashboards/resources/pod.libsonnet
lib/add-runbook-links.libsonnet
lib/utils.libsonnet

This should improve the discoverability and consumption of library files shipped with the project.
List of changes:
- consolidated both `utils.libsonnet` libraries into one
- moved `add-runbook-links.libsonnet` into `lib/` as it can be consumed independently of using mixin
- ran `jsonnetfmt`

*: cleanup

---

rules/kube_apiserver.libsonnet

I've always wanted to make these apiserver SLO latencies default and actually did that back in December and never sent the PR...
Now this is even more important as it fixes the default latencies as asked for in #643...
Currently all apiserver SLO latencies are way to strict and going forward they should match the SIG scalability guidelines again.
Super sorry and hopefully it'll be even easier to adjust if the latencies if you need different ones (although I think that most cluster  should try sticking with the official ones!)

Make apiserver SLO latencies configurable - fixes defaults too

---

dashboards/resources/namespace.libsonnet
dashboards/resources/node.libsonnet
dashboards/resources/pod.libsonnet
rules/apps.libsonnet

The bug was raised downstream in https://bugzilla.redhat.com/show_bug.cgi?id=1913618
Dashboards were displaying cpu and memory requests and limits for pods and jobs that had completed or failed and hence skewed the quotas on the dashboards
cc @paulfantom

CPU and Memory Quota should not include series from workloads that have released resources

---

rules/apps.libsonnet
tests.yaml

The recording rules for:
- namespace_memory:kube_pod_container_resource_requests:sum
- namespace_cpu:kube_pod_container_resource_requests:sum
- namespace_cpu:kube_pod_container_resource_requests:sum
- namespace_memory:kube_pod_container_resource_limits:sum
use cluster in the `sum by` section however `cluster` is not referenced in the final `max by` clause of the rule. This causes queries to return no data.
Updating these rules and queries ensures data is returned.
<details>
<summary> Query as is `namespace_cpu:kube_pod_container_resource_requests:sum`:</summary>
</details>
<details>
<summary> Query with extra `cluster` in `max by` `namespace_cpu:kube_pod_container_resource_requests:sum`:</summary>
</details>

Add cluster to clause in k8s.rules

---

alerts/resource_alerts.libsonnet

As pointed out in #589 we are comparing apples and oranges in KubeCPUOvercommit and KubeMemoryOvercommit alerts. In both cases, we have a percentage of resource requests to total allocatable resources on LHS, but we compare it with the percentage of available nodes. This approach may work in specific cases but is incorrect when non-homogeneous environments are used.
IMHO it would be better to use an alert expression like:
```
total requested resources > (total allocatable resources - total allocatable resources of the largest node)
```
This way we care only about the largest chunk of allocatable resource going away (node down) as clusters can tolerate failures of much smaller nodes.
That expression could be amended to include prevention for single-node clusters and reorganized to allow …

alerts: fix CPU and Memory overcommit alerts

---

alerts/system_alerts.libsonnet

The expression for the KubeClientErrors alert is already grouped by
instance and job labels.  This includes the namespace as well, as many
people find it useful to route alerts based on namespace.

alerts: Include namespace in grouping for KubeClientErrors

---

dashboards/controller-manager.libsonnet
dashboards/kubelet.libsonnet
dashboards/network-usage/cluster-total.libsonnet
dashboards/network-usage/namespace-by-pod.libsonnet
dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/network-usage/pod-total.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/scheduler.libsonnet

Using 'up' for templating variables seems to be a better choice than these often expensive metrics with many dimensions.

Use up metric for templating variables

---

alerts/kubelet.libsonnet
tests.yaml

Fixes #529
This is a noisy alerts when using nodes efficiently, lowering the severity as per
suggestion in #529.

fix(alerts): lower KubeletTooManyPods severity to info

---

alerts/storage_alerts.libsonnet
tests.yaml

This PR co-relates `kubelet_volume_stats_*` against `kube_persistentvolumeclaim_access_mode`
to skip the `KubePersistentVolumeFillingUp` alert on PVCs with access_mode 'ReadOnlyMany'.
This change is inspired from `NodeFilesystemSpaceFillingUp`[1] alert which already
ignores read only mounts using `node_filesystem_readonly` metrics.
[1] https://github.com/prometheus/node_exporter/blob/832909dd257eb368cf83363ffcae3ab84cb4bcb1/docs/node-mixin/alerts/alerts.libsonnet#L15

Skip volume filling up alert for readonly PVC

---

dashboards/resources/cluster.libsonnet
dashboards/resources/multi-cluster.libsonnet

'iowait' and 'steal' indicate specific idle/wait states, which shouldn't
be counted into CPU Utilisation. Also see
https://github.com/prometheus-operator/kube-prometheus/pull/796.
Per the iostat man page:
%idle
Show the percentage of time that the CPU or CPUs were idle and the
system did not have an outstanding disk I/O request.
%iowait
Show the percentage of time that the CPU or CPUs were idle during
which the system had an outstanding disk I/O request.
%steal
Show the percentage of time spent in involuntary wait by the
virtual CPU or CPUs while the hypervisor was servicing another
virtual processor.
Signed-off-by: Julian Wiedmann <jwi@linux.ibm.com>

dashboards/resources: exclude iowait and steal from CPU Utilisation

---

dashboards/resources/namespace.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload.libsonnet

After https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/669 , dashboards are using `kube_namespace_created` metrics for namespace variables, however it is not enabled on [ksm-lite addon](https://github.com/prometheus-operator/kube-prometheus/blame/3b1f268d519455165418ab047decbab1cdd92684/jsonnet/kube-prometheus/addons/ksm-lite.libsonnet#L19).

Use kube_namespace_status_phase metric as namespace selector in dashboards

---

dashboards/network-usage/workload-total.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/resources/multi-cluster.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet

Fixes https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/697
As mentioned in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/675#issuecomment-971004197 when I previously tested locally I didn't realise that I had both kubelet and cadvisor using `job="kubelet"`.

Fix incorrect selectors (kubelet -> cadvisor)

---

dashboards/apiserver.libsonnet
dashboards/controller-manager.libsonnet
dashboards/kubelet.libsonnet
dashboards/proxy.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/pod.libsonnet
dashboards/scheduler.libsonnet
dashboards/windows.libsonnet

There were a handful of queries which still had a hardcoded 5m for `rate`, `irate`, and `increase` queries.
These were all the remaining ones I could find.

Update all dashboards to use `grafanaIntervalVar` from config

---

dashboards/resources/workload-namespace.libsonnet

From the UX perspective, it is always better to place dependent(workload) selector after the source(namespace) selector.

dashboard: namespace selector must appear before workload selector

---

config.libsonnet

This PR simply sets the prefix to an empty string, rather than a dot.
If the default config is used, and no prefix is defined, the `.` breaks the grafana react router and links between dashboards are broken. This results in the first click of the link returning a 404, but if you refresh your browser, it successfully loads the desired dashboard.
By supplying an empty prefix, things work as expected, without the 404/refresh loop.

Set the default link prefix to an empty string. A dot breaks the react router.

---

rules/apps.libsonnet

I found that a handful of recording rules did not have the same labelset for the join/group query, and were subsequently not producing any output.
This fixes a few panels which did not have data in the namespace, node, and pod dashboards.

Satisfy the left join/on for all recording rules in k8s.rules

---

dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet

Some dashboards define a template variable `namespace` without the
option to select multiple values. This commit sets `multi: false`
explicitly and changes the `namespace` label matcher in queries in those
dashboards from regex match (`=~`) to just match (`=`).
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

dashboards: direct match namespace template where multi: false

---

alerts/kube_apiserver.libsonnet
tests.yaml

As in the title.
A cluster can have multiple API Servers, so let's clarify which one those alerts are relating to.

alerts: clarify about which API server those alerts are

---

alerts/resource_alerts.libsonnet
tests.yaml

Some k8s ResourceQuota object seem to using `requests.cpu` and
`requests.memory` to specify compute resource quotas. According to the
doc[1], it should be treated similar as `cpu` and `memory`.
[1] https://kubernetes.io/docs/concepts/policy/resource-quotas/#compute-resource-quota

fix: Consider `requests.(cpu|memory)` for quota overcommit alerts

---

dashboards/resources/workload-namespace.libsonnet

Extra "}" added as part of #675 which breaks the namespace label query.

"Compute Resources / Namespace (Workloads)" dashboard is broken

---

alerts/storage_alerts.libsonnet
config.libsonnet
tests.yaml

Fixes #710 
Certain workloads, by design will provision a persistent volume that is
entirely 'full' from the outset. Such an example is KubeVirt CDI
where the file is a disk image, and the underlying PV will be the exact
size of the allocated file. This causes the KubePersistentVolumeFillingUp
storage alerts to fire as soon as they are evaluated, despite the fact
that the data in the volume has reached its maximum size.
This change provides a mechanism which allows cluster admin
to label the PVC in advance and avoid the alerts from ever
firing in these known situations.

Add ability to mark expected expected 'full volumes' via PVC label

---

dashboards/apiserver.libsonnet
dashboards/controller-manager.libsonnet
dashboards/defaults.libsonnet
dashboards/kubelet.libsonnet
dashboards/persistentvolumesusage.libsonnet
dashboards/proxy.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/resources/multi-cluster.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/node.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet
dashboards/scheduler.libsonnet
dashboards/windows.libsonnet

To make dashboards coherent it would be good to reset some fields to common values. Since we do have `defaults.libsonnet` it looks like a good place to include such common values.
Changes from this PR:
- move setting dashboard refresh rate to `defaults.libsonnet`
- move setting dashboard tags  to `defaults.libsonnet`
- set `minimumTimeInterval` for all panels
- move all legend parts of all panels to the right

dashboards: use defaults.libsonnet for setting common values

---

dashboards/resources/workload.libsonnet

Prior to this change, `Compute Resources / Workload` dashboard had
`namespace > workload > type` as filters where `type` mearly used as
a label rather a filter.
This commit brings a change in the UX, now the filtering order has changed to
`namespace > type > workload` and all of those filters are actually
functions like a filter.
For example, from now on the user should able to select namespace, then select
the type of workload and finally the actual workload.

Change ordering of workload type and workload in `Compute Resources /Workload`

---

dashboards/resources/node.libsonnet

This adds a dashed line (hidden by default) to CPU and Memory panels in node dashboard (similar to how `limits` lines are done for pod dashboards). It should improve MTTR in cases where node goes down due to memory exhaustion.
How it looks on dashboard opening:
How it looks after selecting `max capacity` from legend:

dashboards/resources: add max CPU and memory capacity to node dashboards

---

alerts/resource_alerts.libsonnet

This change makes the output for large byte values more readable

alerts: Humanize KubeMemoryOvercommit byte value

---

dashboards/network-usage/namespace-by-workload.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet

Some dashboards define a template variable `namespace` without the
option to select multiple values. This commit sets `multi: false`
explicitly and changes the `namespace` label matcher in queries in those
dashboards from regex match (`=~`) to just match (`=`).
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
(cherry picked from commit ac0ef0a05393e27bcca580ac2306a2ce93dca674)
backport of #705

release-0.9: dashboards: direct match namespace template where multi: false

---

runbook.md

Anchors in runbook.md don't always resolve when clicking on links in the alertmanager notifications, like this: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/runbook.md#alert-name-kubenodeunreachable
This flushes out the runbook.md with more descriptions. I also reordered them to be in the order of [kubelet.sonnet](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/2b27a09a667091cef74776b690ccceaf55995e29/alerts/kubelet.libsonnet) to make it easier to update later.

updating documentation so links from alertmanager to specific alerts work

---

rules/kubelet.libsonnet

This change fixes an error in one of the kubelet rules which could error due to a one to many join. This error occurs if you have multiple clusters with nodes that have identical IPs. Adding the cluster labels differentiates the time series and solves the problem.

Add cluster labels to kubelet rules

---

config.libsonnet
dashboards/resources/cluster.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/pod.libsonnet

**Changes Overview:**
config.libsonnet: Add `containerfsSelector`
dashboards: Replace `container!=""` with `containerfsSelector` on `container_fs*` metrices
Adds `diskDeviceSelector` to avoid double accounting of data
Adds namespace!="" on container_fs* queries to avoid  results with empty namespace
This commit adds a new selector named containerfsSelector.
This will be helpful in overidding this config on systems
not having container series in their container_fs* metric.
Additional details on why this will be helpful for systems that can drop the container series from container_fs* metrics : https://github.com/prometheus-operator/kube-prometheus/pull/1402
Signed-off-by: Jayapriya Pai <slashpai9@gmail.com>

Add containerfsSelector and update queries having container_fs*

---

rules/kube_apiserver.libsonnet

Follow-up PR to https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/740 updating the `cluster_quantile:apiserver_request_duration_seconds:histogram_quantile` with the new kubeApiserverNonStreamingSelector.
I also removed the `cluster_quantile:apiserver_request_duration_seconds:histogram_quantile` that only has the `quantile` label since it wasn't used anywhere and wasn't bringing any value.

Exclude long-running requests from cluster_quantile:apiserver_request_duration_seconds:histogram_quantile

---

.github/workflows/ci.yaml
Makefile

This commit refactors makefile lint targets into specific/small
targets and also adds dedicated Github actions for better error message
readability.
Also fixes https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/741

Add separate lint target for alerts, jsonnet and dashboards

---

dashboards/kubelet.libsonnet

Clarify node template variable in kubelet dash

---

dashboards/resources/cluster.libsonnet
dashboards/resources/multi-cluster.libsonnet
rules/node.libsonnet

- Updates cluster resources dashboards to use precomputed `cluster:node_cpu:ratio_rate5m` metric. the current query is slower to evaluate on clusters having many nodes with multi-core cpus ( cores >= 64 ).
cc @povilasv @paulfantom

use recording rule metric for cluster cpu utilization

---

alerts/kubelet.libsonnet

Simple fix to KubeletPodStartUpLatencyHigh so that it works with multiple clusters. Issues are experienced when the instance label, normally an IP, is identical between two clusters. This causes a one to many error.

Fix KubeletPodStartUpLatencyHigh to work with multiple clusters

---

alerts/apps_alerts.libsonnet
config.libsonnet
runbook.md
tests.yaml

* KubeJobCompletion sounds like an info rather than a warning.
* Existing expression is not accounting the failed jobs which leads to false positive firing of alert.
Co-authored-by: W. Trevor King <wking@redhat.com>

Rename KubeJobCompletion to KubeJobNotCompleted and fix alert expression

---

alerts/apps_alerts.libsonnet
alerts/kube_apiserver.libsonnet
alerts/system_alerts.libsonnet

A handful of alerts did not include the cluster label when doing aggregations.
As a result, in a multi-cluster environment, it could be difficult to identify which cluster was triggering the alert. Also, in some cases (such as the KubeVersionMismatch), differences between clusters would be mistakenly reported as alerts.
This resolves (portions of? possibly all?) #695
I tested the ones that I changed, which we received feedback on. I *believe* all the other alert queries are fine from a cursory review. They do not seem to have aggregations, which would remove the cluster label if present.
It's possible I still missed some tho.

Add cluster label to aggregations in alert queries

---

config.libsonnet

I had added deviceDeviceSelector in container_fs* queries as part of [kubernetes-mixin PR](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/737) since [diskDeviceSelector](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/config.libsonnet#L100-L101) includes only node_exporter label values this commit tries to add cadvisor device as well
@paulfantom I am not sure if this is the right way but `diskDeviceSelector: 'device=~"(/dev/)?%s"' % std.join('|', self.diskDevices),` was not working.  wdyt?

Update diskDeviceSelector to include cadvisor device

---

rules/kube_apiserver-availability.libsonnet

Addresses https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/975 by reordering the count/bucket rules, and reusing the `*_bucket{le="+Inf"}` value in the `*_count` expression to ensure they amount to the same value (which is needed as it is a prerequisite to the SLO rules expressions).

feat: API Server availability rules consistency

---

dashboards/resources/multi-cluster.libsonnet

With this, the average CPU utilization across clusters is calculated instead of listing the CPU util per cluster.
This fixes the visuals of the panel and brings it in line with the other panels in the row, which all display an average.

fix: calculate average CPU util

---

scripts/go.mod
scripts/go.sum

CVE-2024-0406 affects mholt/archiver v3.5.1, there is a fix in v3.5.2 but the [PR](https://github.com/mholt/archiver/pull/396) has remained open since January 2024.
This PR introduces a replace directive to use the same fork that the Gitea project [selected](https://github.com/go-gitea/gitea/pull/31267).

chore(deps): Address CVE-2024-0406

---

alerts/apps_alerts.libsonnet
alerts/resource_alerts.libsonnet

1) [CPUThrottlingHigh: change aggregation to without to keep external labels](https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/8900abe9c1645f44df2b5051e67ab6a5173ee518) 
And add cadvisorSelector selector.
2) [KubeContainerWaiting: remove sum by, to keep external labels. Add reason into description](https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/76e957da5e1649afbfe90f31a532617d23a8edad)

Update CPUThrottlingHigh and KubeContainerWaiting alerts

---

alerts/apps_alerts.libsonnet
tests.yaml

For bigger Kubernetes clusters with bigger node churn (for instance,
cloud clusters with spot nodes), the daemonset rollouts often get stuck
for longer than just 15 minutes. Since the alert might easily misfire
even in cases where the delay is legitimate.
This PR introduces configurable `for` value to allow for customization.
As a default, the original value `15m` is left, so the only real
difference would be a slight change in the alert message formatting.
Signed-off-by: Milan Plzik <milan.plzik@grafana.com>
<details>
<summary>Details</summary>
</details>
Fixes #

Make the daemonset rollout stuck alert configurable.

---

alerts/kube_apiserver.libsonnet

Supersede of https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/774
@skl please let me know what you think about this ;)

fix(alerts): add instance label to KubeAggregatedAPIErrors

---

.github/dependabot.yaml

Configures Dependabot to keep an eye on `scripts/go.mod` (we're currently checking only GitHub Actions).

build(deps): Enable dependabot for Golang

---

rules/kube_apiserver-availability.libsonnet

In #976 I introduced a bug because I didn't remove the multiplication by `* 24 * SLODays` from the count expression, despite it now relying on the bucket infinity of the (already multiplied) one.
This causes the `apiserver_request_sli_duration_seconds_count` to end up being multiplied twice by `* 24 * SLODays`, leading to the faulty Availability calculations reported in:
- #990
- https://github.com/prometheus-operator/kube-prometheus/issues/2564
- https://github.com/prometheus-community/helm-charts/issues/5043.
This PR should fix the error

fix: apiserver availability apiserver_request_sli_duration_seconds_count:increase30d

---

.pint.hcl

Since pint lint is failing all the time because of the same lint issue, I think that we could temporarily disable that specific lint check to stop having the CI always fail.
I followed the docs [here](https://cloudflare.github.io/pint/ignoring.html#disabling-checks-globally) to understand how to disable it.
- #986
- #985

fix: pint lint issue temporary workaround

---

dashboards/resources/node.libsonnet

Fixes #999
Changes:
- Fixed incorrect panel title
- We now have two memory charts on the node (pods) dashboard, one with cache and one without

fix(dashboards): Graph mem usage w and w/o cache

---

rules/kube_apiserver-availability.libsonnet
rules/kube_apiserver-burnrate.libsonnet
rules/kube_apiserver-config.libsonnet

This PR takes the work and feedback from #965 and #1006 and brings it into a single PR which:
- Updates the API Server availability and burn-rate recording rules to support both Prometheus v2 `{le="1"}` and v3 `{le="1.0"}` histogram bucket formats. This is achieved through the use of regex matchers to make the decimal part optional.
- Also updates some matchers which were missed in #965
- N.B. double-double-escaped regex required (once for jsonnent and once for Prometheus).
I did an ad-hoc benchmark of query latency difference for the `apiserver_request:availability30d` recording rule on a fleet of clusters and saw no significant differences when using the regex matchers in this PR.
Supersedes #965 #1006
Fixes #1005

fix(rules): handle apiserver normalized buckets

---

dashboards/controller-manager.libsonnet
dashboards/kubelet.libsonnet
dashboards/proxy.libsonnet
dashboards/scheduler.libsonnet

url label hasn't been used since kubernetes v1.24.
relevant commit:
https://github.com/kubernetes/component-base/commit/fd4965b740ab02761ec23ec5c0a40c2cd5e4a3e2

removed deprecated label `url` of rest_client_request_duration_seconds_bucket

---

alerts/apps_alerts.libsonnet
alerts/kube_apiserver.libsonnet
alerts/kubelet.libsonnet
alerts/resource_alerts.libsonnet
alerts/system_alerts.libsonnet

This PR has two sets of changes:
- Adds the `cluster` label to any alert description where it was missing (currently inconsistent)
- More robust de-dupe of pod count in `KubeletTooManyPods` alert
Fixes #997.

feat: de-dupe KubeletTooManyPods, add cluster to descriptions

---

alerts/kubelet.libsonnet
tests.yaml

Hello,
First time contributing to this repo and writing jsonnet so I welcome any feedback on the syntax that I've used here.
In my personal experience at #dayjob we get many false alerts on nodes which are undergoing maintenance.  I believe filtering out cordoned nodes from these alerts is something many people would benefit from.  Thoughts?
Thank you

feat: filter NodeReadiness alerts on uncordoned status

---

alerts/kubelet.libsonnet
tests.yaml

Resolves duplicate series error with KubeletTooManyPods alert:
- Previous query used a per-node pod count, which is expensive and prone to duplicate-series errors with pods of the same name and different `uid`
- I wanted to avoid depending on `uid` as many people drop this label due to high cardinality
- `kubelet_running_pods` metric already exists and gives a per-node count of running pods, alleviating the need to counts the pods per node in the first place
Added a test for multi-node scenario.
Fixes #1015

fix: KubeletTooManyPods duplicate series error

---

dashboards/dashboards.libsonnet
dashboards/windows.libsonnet
rules/rules.libsonnet

disabling `Multi-value` selection option for the `instance` variable  and other small fixes. (#980)

fix(dashboards): fix `USE Method / Node(Windows)` dashboard

---

alerts/kubelet.libsonnet
tests.yaml

Turns out there's a variety of Kubelet scrape configurations out there:
- Some use `instance` label as node IP address, others use this label as the node name
- Some use `node` label as the name name, others don't have this label
- `kubelet_node_name` does have a `node` label which seems a consistent source of the node name
This PR updates the `KubeletTooManyPods` alert to source the node name from `kubelet_node_name` and updates the tests to represent the inconsistent scrape configs.
Fixes #1015

fix(KubeletTooManyPods): handle inconsistent instance labels

---

alerts/kubelet.libsonnet

Corrected the issue in #1021  where `KubeletTooManyPods` did not use `%(clusterLabel)s` and instead specified `cluster`.

fix: KubeletTooManyPods respect clusterLabels

---

.github/workflows/release.yaml
README.md

This PR:
- Adds a github action that is triggered when a new tag is pushed. The github action autogenerates a changelog on release.
- Adds the command for releasing in readme.

chore: automate-release-process

---

alerts/apps_alerts.libsonnet
tests/tests.yaml

According to [0] and [1] `kube_statefulset_status_replicas` returns "the number of Pods created by the StatefulSet controller". Therefore this alert only fires when the StatefulSet controller is able to create the pod, but it does not get ready.
In cases where the controller is unable to create the pod (e.g. invalid pod spec) this alert does not fire.
This is contrary to the expectation of firing when the statefulset does not match the configured amount of replicas.
[0]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#statefulsetstatus-v1-apps
[1]: https://github.com/kubernetes/kube-state-metrics/blob/2a95d4649b2fea55799032fb9c0b571c4ba7f776/internal/store/statefulset.go#L75

Use `kube_statefulset_replicas` for `KubeStatefulSetReplicasMismatch`

---

README.md
dashboards/resources/cluster.libsonnet
dashboards/resources/multi-cluster.libsonnet
dashboards/resources/namespace.libsonnet
dashboards/resources/node.libsonnet
dashboards/resources/pod.libsonnet
dashboards/resources/workload-namespace.libsonnet
dashboards/resources/workload.libsonnet
rules/apps.libsonnet
tests/tests.yaml

From discussion in [this issue](https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/670#issuecomment-2417230968), this PR adds a rate version of the irate rule introduced from [this PR](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/619).
Also updates dashboards to use the new rate version of the rule.
Existing recording rule `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate` will be kept for backwards-compatibility.
We tested a sum on the `irate` query (to avoid hitting limits when too many series are returned):
```bash
sum(
sum by (cluster, namespace, pod, container) (
irate(container_cpu_usage_seconds_total{image!="",job="kube-system/cadvisor"}[5m])
) 
* on (cluster, namespace, pod) group_left (node) 
topk by (cluster, namespace, …
```

feat: new container cpu usage recording rule using rate()

---

dashboards/windows.libsonnet
rules/windows.libsonnet

Since **windows-exporter 0.30.0**, the `windows_system_system_up_time` metric has been renamed to `windows_system_boot_time_timestamp_seconds`.
https://github.com/prometheus-community/windows_exporter/releases/tag/v0.30.0

fix: rename windows_system_system_up_time metric

---

alerts/apps_alerts.libsonnet
rules/rules.libsonnet
runbook.md
tests/apps_alerts-test.yaml

feat(alerts): New KubePdbNotEnoughHealthyPods alert

---

alerts/apps_alerts.libsonnet
tests/apps_alerts-test.yaml

Fixed the bug reported in #1062 according to the proposed solution.

Fixed label mistmatch in rule "KubeStatefulSetUpdateNotRolledOut" in Group "kubernetes-apps" 

---

rules/kubelet.libsonnet
tests/kubelet-test.yaml

**Why**
When the right hand-side of the operations returns multiple matches, the rules fail. 
This fix aim to prevent such failure.

fix: kubelet rules group_left

---

config.libsonnet
rules/apps.libsonnet
tests/rules-pod-owner-test.yaml

This PR fixes a bug where the `namespace_workload_pod:kube_pod_owner:relabel` metric returns inconsistent data for the `workload_type` label.
This is particularly painful when a downstream user wants to use this metric to do vector matching with other metrics that have a `workload_type` or `owner_kind` type label.
Some more rationale... the raw KSM metrics seem to prefer singular PascalCase values for this label. Seeing as this is a relabeling of KSM metrics, we should probably abide by the upstream preference for consistency.
<details>
<summary>Details - rendered diffs</summary>
```console
user@host kubernetes-mixin % ls -la orig new         
new:
total 168
drwxr-xr-x   5 user  staff    160 Jul 16 00:49 .
drwxr-xr-x@ 32 user  staff   1024 Jul 16 00:50 ..
drwxr-xr-x  24 user  staff    768 …
```

fix(k8s.rules.pod_owner): Make workload_type label values consistent with upstream metrics and across generated series
