- README.md
Just running through this.
Also want to show example of how to override the selectors, but that can wait.
> More tweaks to the readme.

- README.md
- alerts/apps_alerts.libsonnet
- alerts/resource_alerts.libsonnet
- alerts/storage_alerts.libsonnet
- alerts/system_alerts.libsonnet
- config.libsonnet
- dashboards/node.libsonnet
- dashboards/pods.libsonnet
- dashboards/resources.libsonnet
- dashboards/statefulset.libsonnet
- dashboards/use.libsonnet
- lib/alerts.jsonnet
- lib/dashboards.jsonnet
- lib/rules.jsonnet
- rules/rules.libsonnet
Albeit not our favorite, let's go with what's the convention throughout the jsonnet community.
@tomwilkie
> *: Use camelcase convention of jsonnet

- README.md
> Add commands for generating rules + dashboards to the readme.

- dashboards/resources.libsonnet
Pod resources dashboard was still showing the POD container on graphs.
> Remove POD container from Pod resources dashboard

- LICENSE
Need LGTMs from ~@brancz~, ~@StevenACoffman~, ~@adamdecaf~, @dimm0, ~@metalmatze~, ~@richerve~ 
Thanks!
> Add Apache 2.0 license.

- dashboards/resources.libsonnet
> Add CPU and Memory utilisation headlines.

- alerts/system_alerts.libsonnet
RE https://github.com/coreos/prometheus-operator/issues/1631#issuecomment-414299329
@tomwilkie @metalmatze 
cc @mxinden @squat @s-urbaniak
> alerts: Ignore 404 errors in client errors alert

- alerts/apps_alerts.libsonnet
- alerts/resource_alerts.libsonnet
- alerts/storage_alerts.libsonnet
- config.libsonnet
Closes #56
@tomwilkie @metalmatze 
cc @mxinden @squat @s-urbaniak
> Allow scoping alerts to namespaces

- alerts/apps_alerts.libsonnet
This was causing a circleci test (which is run when a PR is created in this repo) to fail.
cc @metalmatze.
> Fix syntax error.

- alerts/apps_alerts.libsonnet
- alerts/resource_alerts.libsonnet
- alerts/storage_alerts.libsonnet
- alerts/system_alerts.libsonnet
This commit improves the readability of alert messages, fixes typos, and improves consistency.
cc @brancz @metalmatze @s-urbaniak
> alerts: improve readability, fix typos

- alerts/apps_alerts.libsonnet
> Add alert for stateful sets that haven't been updated.

- alerts/resource_alerts.libsonnet
- dashboards/node.libsonnet
- dashboards/resources.libsonnet
- dashboards/use.libsonnet
- rules/rules.libsonnet
some of the graphs has no dada due to broken templating and expr's
@tomwilkie @brancz
> update the node exporter metrics

- config.libsonnet
- dashboards/node.libsonnet
- rules/rules.libsonnet
add prometheus rules to get inodes data
verified in production env
> add recording rules to get inodes data

- .circleci/Dockerfile
- .circleci/config.yml
> Don't commit the jsonnet binary, put build instructions in a Dockerfile.

- config.libsonnet
> config.libsonnet: add devicemapper devices

- dashboards/pods.libsonnet
This PR adds a target line for cpu request and cpu limits on the CPU usage graph.
> add cpu limits and requests on CPU usage

- dashboards/pods.libsonnet
Although this does not give exact restart ocurrences in case of restart loop, this gives a good representation of what is happening.
> Pod dashboard: add restart annotation.

- dashboards/resources.libsonnet
The table currently has an extra label which causes all of the columns
to be mislabeled.
I am guessing I messed up a rebase somewhere...
> Fix Memory Requests table in Cluster dashboard

- README.md
Is there anything else we're missing to cut a release for this repository?
Once this PR is merged I'll tag the merge commit as `v0.1.0` and push directly to `master` and then create branch off `release-0.1`.
/cc @brancz @csmarchbanks @tomwilkie
> Add Releases section to README to indicate Kubernetes compatibility

- alerts/resource_alerts.libsonnet
change node resouce to  node allocatable resource from kubelet
> fix KubeCPUOvercommit and KubeMemOvercommit alert rule error

- dashboards/resources.libsonnet
change  node:node_num_cpu:sum to kube_node_status_allocatable_cpu_cores
change node_memory_MemTotal_bytes:sum to kube_node_status_allocatable_memory_bytes
> change  node:node_num_cpu:sum to kube_node_status_allocatable_cpu_cores

- alerts/apps_alerts.libsonnet
> Add phase=~"Failed" to KubePodNotReady alert

- alerts/apps_alerts.libsonnet
- alerts/system_alerts.libsonnet
- runbook.md
Updated alert duration from 1h to 15m to allow getting them quicker. Let me know if there are any more that make more sense to change or if I should switch any back.
> switched alerts from 1h to 15m

- rules/rules.libsonnet
> rules: remove duplicate namespace:container_memory_usage_bytes:sum

- dashboards/resources.libsonnet
Fix this typo.
/cc @s-urbaniak
> Fix typo in Memory Usage (Swap) in resource dashboard

- dashboards/resources.libsonnet
Follow up to #244.
/cc @metalmatze
> Fix typo in Memory Usage (Swap)

- alerts/system_alerts.libsonnet
- tests.yaml
cc @brancz @metalmatze @tomwilkie please take a look, thanks!
Supersedes https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/135
> alerts/system_alerts.libsonnet: Improve KubeletTooManyPods alert

- .circleci/Dockerfile
- .circleci/config.yml
I also updated the version of jsonnet while I was at it.
Hopefully I will have some time soon and build a pipeline for this.
cc: @brancz
> Upgrade build image

- dashboards/resources.libsonnet
- rules/rules.libsonnet
If a node CPU/memory usage high, we need know Pods CPU/memory  usage on the node.
> Add k8s-resources-node dashboard

- config.libsonnet
Backport from master to release-0.1
> Use relative drill down links, fixes #192

- dashboards/apiserver.libsonnet
- dashboards/controller-manager.libsonnet
- dashboards/kubelet.libsonnet
- dashboards/persistentvolumesusage.libsonnet
- dashboards/pods.libsonnet
- dashboards/proxy.libsonnet
- dashboards/resources.libsonnet
- dashboards/scheduler.libsonnet
- dashboards/statefulset.libsonnet
- dashboards/windows.libsonnet
On some dashboards all namespace names where in random order when using the variable dropdown.
I can't stand it anymore. :joy:
> Alphabetically sort template variables in dashboards

- alerts/kube_apiserver.libsonnet
- rules/apps.libsonnet
More importantly, of course, this help to remind people that
Prometheus regexp's are always anchored.
> Colossal simplification of regexp's

- README.md
- alerts/storage_alerts.libsonnet
- tests.yaml
KubePersistentVolumeFullInFourDays - Proposal to increase the "for" clause for the alert. #262
> #262 - KubePersistentVolumeFullInFourDays - evaluation period from 5m > 1h

- dashboards/pods.libsonnet
I missed this one in #238, so here is a follow-up.
> use container_memory_working_set_bytes to represent memory usage

- dashboards/network-usage/cluster-total.libsonnet
- dashboards/network-usage/namespace-by-pod.libsonnet
- dashboards/network-usage/namespace-by-workload.libsonnet
- dashboards/network-usage/pod-total.libsonnet
- dashboards/network-usage/workload-total.libsonnet
- dashboards/resources.libsonnet
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>
> Fix: #290 Use datasource variable

- dashboards/controller-manager.libsonnet
> Removing quotes from the boolean values

- dashboards/apiserver.libsonnet
- dashboards/kubelet.libsonnet
- dashboards/proxy.libsonnet
- dashboards/scheduler.libsonnet
> removing quotes from the boolean values in all files

- alerts/kube_apiserver.libsonnet
- rules/kube_apiserver.libsonnet
Backport #304 
/cc @s-urbaniak
> Port KubeAPILatencyHigh alert

- dashboards/apiserver.libsonnet
Added cluster selector to api server dashboard
> support multicluster in api server dashboards

- lib/promgrafonnet/promgrafonnet.libsonnet
Remove import of missing file from release-0.1 branch.
> Remove reference to missing file

- rules/apps.libsonnet
- rules/node.libsonnet
I've added some Prometheus rules to get multicluster graphs running.
> Add Prometheus rules for multicluster deployment

- dashboards/apiserver.libsonnet
Replaced `intance` with `instance`
> Fix promql typo in in etcd cache rate graph

- alerts/kube_apiserver.libsonnet
Metrics on both side have different labels => join on job needed
> Fixed KubeClientCertificateExpiration

- alerts/kube_apiserver.libsonnet
back ports https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/355
> alerts when an aggregation API is down or it reports errors

- dashboards/resources.libsonnet
- dashboards/resources/cluster.libsonnet
- dashboards/resources/multi-cluster.libsonnet
- dashboards/resources/namespace.libsonnet
- dashboards/resources/node.libsonnet
- dashboards/resources/pod.libsonnet
- dashboards/resources/workload-namespace.libsonnet
- dashboards/resources/workload.libsonnet
- rules/node.libsonnet
> Format dashboards & rules

- dashboards/resources.libsonnet
- dashboards/resources/cluster.libsonnet
- dashboards/resources/multi-cluster.libsonnet
- dashboards/resources/namespace.libsonnet
- dashboards/resources/node.libsonnet
- dashboards/resources/pod.libsonnet
- dashboards/resources/workload-namespace.libsonnet
- dashboards/resources/workload.libsonnet
- rules/apps.libsonnet
- rules/node.libsonnet
- tests.yaml
xref https://bugzilla.redhat.com/show_bug.cgi?id=1802941
> Fix potential many-to-many errors

- config.libsonnet
- dashboards/apiserver.libsonnet
- dashboards/controller-manager.libsonnet
- dashboards/kubelet.libsonnet
- dashboards/persistentvolumesusage.libsonnet
- dashboards/proxy.libsonnet
- dashboards/resources/cluster.libsonnet
- dashboards/resources/namespace.libsonnet
- dashboards/resources/node.libsonnet
- dashboards/resources/pod.libsonnet
- dashboards/resources/workload-namespace.libsonnet
- dashboards/resources/workload.libsonnet
- dashboards/scheduler.libsonnet
- dashboards/windows.libsonnet
output of `make fmt`
We need some tool which checks this before allowing merging as this keeps hapenning
> Format dashboards and rules

- dashboards/resources/cluster.libsonnet
- dashboards/resources/multi-cluster.libsonnet
- dashboards/resources/namespace.libsonnet
- dashboards/resources/node.libsonnet
- dashboards/resources/pod.libsonnet
- dashboards/resources/workload-namespace.libsonnet
- dashboards/resources/workload.libsonnet
Ref https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/353
> Use $__interval  for resources dashboards

- alerts/kube_apiserver.libsonnet
Those were replaced by more granular one and never deleted causing duplicate alerts.
/cc @brancz @metalmatze
> alerts: remove outdated api server alerts

- dashboards/dashboards.libsonnet
- dashboards/statefulset.libsonnet
Added back statefulset dashboard that was removed in #362
> return statefulset dashboard

- alerts/kubelet.libsonnet
> alerts/kubelet.libsonnet: Extend KubeletPodStartUpLatencyHigh to 60

- OWNERS
I was given some powers here to cut branches, so I offer to help out more in this repository.
Kindly asking to become one of the owners of this repo :)
Signed-off-by: Sergiusz Urbaniak <sergiusz.urbaniak@gmail.com>
cc @tomwilkie @csmarchbanks @brancz @metalmatze
> OWNERS: add s-urbaniak

- dashboards/resources/cluster.libsonnet
- dashboards/resources/namespace.libsonnet
- dashboards/resources/pod.libsonnet
- dashboards/resources/workload-namespace.libsonnet
- dashboards/resources/workload.libsonnet
$interval variable changed to $__interval
> Interval variable fixed

- alerts/apps_alerts.libsonnet
Fix https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/395
> Change cause based alerts to warning

- config.libsonnet
> Remove the now unneeded slo.libsonnet import

- alerts/kube_apiserver.libsonnet
REF https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/401
> Remove AggregatedAPIDown alert from 0.3-release

- alerts/apps_alerts.libsonnet
- rules/apps.libsonnet
- rules/node.libsonnet
- tests.yaml
xref https://bugzilla.redhat.com/show_bug.cgi?id=1812006
> Fix potential 'many-to-many matching' errors

- alerts/apps_alerts.libsonnet
- rules/apps.libsonnet
- rules/node.libsonnet
- tests.yaml
Specifically this change backports #361 and #419 in the `release-0.3` branch.
> Cherry pick fixes for "many-to-many" errors

- rules/kube_apiserver.libsonnet
> Add DELETECOLLECTION to long-running apiserver verbs

- README.md
I'm more happy with this solution, since it addresses the issue overriding any single alert properties.
> issue-425: Documentation for alert extraAnnotations

- README.md
- alerts/resource_alerts.libsonnet
- runbook.md
This fixes #441 according to my proposal made in the comments https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/441#issuecomment-647032780
> alerts/resource_alerts.libsonnet, runbook.md: Reduce KubeQuotaExceeded severity and adjust threshold

- alerts/resource_alerts.libsonnet
Reducing alert severity as per https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/108#issuecomment-651711524
> alerts: reduce severity of CPUThrottlingHigh alert

- alerts/kubelet.libsonnet
For KubeNodeUnreachable, we can ignore the impending-node-termination
that is set by GCE preemptible VMs.
This also moves the keys to a configurable list so it can be expanded
for other cloud providers (AWS Spot instances?) or custom solutions.
fixes #459
> ignore cloud.google.com/impending-node-termination

- alerts/system_alerts.libsonnet
Fixes https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/342
> tolerate kubernetes component minor versions skew

- README.md
- alerts/resource_alerts.libsonnet
- runbook.md
alerts/resource_alerts.libsonnet, runbook.md: Reduce KubeQuotaExceeded severity and adjust threshold
This PR is needed in order for those changes  to land in [cluster-monitoring-operator](github.com/openshift/cluster-monitoring-operator)
> Cherry-pick pull request #450 from RiRa12621/master

- README.md
added information about prom-metrics-check tool
> updated README, added note about prom-metrics-check tool

- README.md
Signed-off-by: Sergiusz Urbaniak <sergiusz.urbaniak@gmail.com>
> README: cut 0.5 release and update compatibility matrix

- alerts/apps_alerts.libsonnet
- alerts/kube_apiserver.libsonnet
- alerts/kubelet.libsonnet
- alerts/resource_alerts.libsonnet
- alerts/storage_alerts.libsonnet
- alerts/system_alerts.libsonnet
- lib/absent_alert.libsonnet
- tests.yaml
* replaced `message` annotation field with `description`
* added simple `summary` field
Guidelines: https://monitoring.mixins.dev/#guidelines-for-alert-names-labels-and-annotations
/cc @brancz @beorn7
> Adhere to monitoring mixins annotation guidelines

- alerts/apps_alerts.libsonnet
- tests.yaml
Cherry-picking #402 so we have the possibility to have this as part of OCP 4.5.z
> Cherry-pick: Change cause based alerts to warning

- alerts/resource_alerts.libsonnet
- runbook.md
backport the changes in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/494
> release-0.5: Split the alerts for quota usage reached and exceeded

- alerts/resource_alerts.libsonnet
- runbook.md
> release-0.4: Split the alerts for quota usage reached and exceeded

- dashboards/windows.libsonnet
- rules/windows.libsonnet
During PR https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/503 I messed up 2 rules.
I have corrected them in this PR.
> Fixed type in rule

- config.libsonnet
Add SD cards to the list of devices to monitor
> Update config.libsonnet to add SD cards to the list of block devices to monitor

- dashboards/apiserver.libsonnet
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
> dashboards/apiserver.libsonnet: fix typo gurantees -> guarantees

- dashboards/network-usage/cluster-total.libsonnet
- dashboards/network-usage/namespace-by-pod.libsonnet
- dashboards/network-usage/namespace-by-workload.libsonnet
- dashboards/network-usage/pod-total.libsonnet
- dashboards/network-usage/workload-total.libsonnet
As in the resource graphs, setting up multi-clustering
Add a template for cluster selection
Modify target to take cluster in queries
> Enable multi-cluster in Network dashboards

- dashboards/network-usage/namespace-by-workload.libsonnet
> dashboards/network-usage: remove duplicate cluster selector

- alerts/apps_alerts.libsonnet
> Adjust time window for KubePodCrashLooping alert

- dashboards/resources/workload-namespace.libsonnet
Fixes bug introduced in 41029ffd96bc963a6691f4175f6557cb52250928
> Substituting clusterLabel value to fix variable definition

- dashboards/controller-manager.libsonnet
- dashboards/scheduler.libsonnet
Hi,
After building, the $cluster variable was missing from controller manager and scheduler dashboards. I went trough both libsonnet and made a few changes so the variable can show up in both of them.
> Add $cluster variable to some dashs

- dashboards/proxy.libsonnet
Hi,
I added the $cluster to one more dashboard that missed it (proxy.libsonnet). The same changes has been made like previous commits #563 .
> Add $cluster variable to proxy dashboard

- dashboards/resources/cluster.libsonnet
- dashboards/resources/namespace.libsonnet
- dashboards/resources/pod.libsonnet
- dashboards/resources/workload-namespace.libsonnet
- dashboards/resources/workload.libsonnet
Instead of giving every panel its own row with the same name.
> Add only one Network row for all network panels

- README.md
New release branch to allow merging https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/534
/cc @lilic @brancz
> README: cut release-0.7

- alerts/kube_apiserver.libsonnet
- dashboards/resources/cluster.libsonnet
- dashboards/resources/namespace.libsonnet
- dashboards/resources/pod.libsonnet
- dashboards/resources/workload-namespace.libsonnet
- dashboards/resources/workload.libsonnet
Hi,
To make sure everything runs fine, we decided to stay on the 0.7 release, but it misses important fix like the cluster dashboard issue where the network rows were compacted. So I decided to grab all needed fixes and push this PR so this release could work correctly.
> Add fixes to release 0.7

- dashboards/resources/cluster.libsonnet
Fixing a typo in dashboard query.
> dashboards/resources: fix typo

- rules/kube_apiserver.libsonnet
Hi guys! I found that api-server dashboard does not work in multi-cluster mode. The reason is that the metrics from the rules do not have a cluster label
> Fix api server support multi cluster

- dashboards/resources/namespace.libsonnet
Update spelling for memory utilisation panel title since all other panels are using the spelling `utilisation` rather than `utilization`
> Update memory utilisation panel title

- dashboards/resources/namespace.libsonnet
- dashboards/resources/pod.libsonnet
Backport PR #608 -Fixed Resources Dashboard Storage IO components
Signed-off-by: Anmol Sachan <anmol13694@gmail.com>
> Backport PR #608 -Fixed Resources Dashboard Storage IO components

- dashboards/controller-manager.libsonnet
- dashboards/scheduler.libsonnet
- added ability to group by cluster for controller and scheduler dashboards as per issue #605
> add cluster in group by for controller and scheduler dashboards

- dashboards/resources/cluster.libsonnet
- dashboards/resources/namespace.libsonnet
- dashboards/resources/pod.libsonnet
- dashboards/resources/workload-namespace.libsonnet
- dashboards/resources/workload.libsonnet
Resolves https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/631#issue-927961243
> Update rate-of-packet panels' unit from Bps to pps

- config.libsonnet
- dashboards/defaults.libsonnet
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>
> Configure timezone for Grafana dashboards

- dashboards/resources/cluster.libsonnet
- dashboards/resources/namespace.libsonnet
> release-0.4: Fix TX network queries resources dashboards

- dashboards/resources/cluster.libsonnet
- dashboards/resources/namespace.libsonnet
> release-0.5: Fix TX network queries resources dashboards

- README.md
As in title :)
ping @brancz @metalmatze @s-urbaniak for approval
> *: cut release-0.9 branch

- rules/kube_apiserver.libsonnet
This should speed up calculating these metrics. Similar to #537
> Pre-aggregate apiserver_request_duration_seconds

- dashboards/resources/cluster.libsonnet
- dashboards/resources/multi-cluster.libsonnet
fix the issue introduced in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/667#discussion_r742629004
@paulfantom @julianwiedmann
> fix cpu utilization query in cluster resources dashboards

- dashboards/resources/node.libsonnet
Fix regression introduced in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/669#discussion_r742634559
@paulfantom
> fix template query in node resources dashboard

- dashboards/network-usage/workload-total.libsonnet
- dashboards/persistentvolumesusage.libsonnet
- dashboards/resources/cluster.libsonnet
- dashboards/resources/multi-cluster.libsonnet
- dashboards/resources/namespace.libsonnet
- dashboards/resources/pod.libsonnet
- dashboards/resources/workload-namespace.libsonnet
- dashboards/resources/workload.libsonnet
> Add missing job selectors to dashboards

- .github/workflows/ci.yaml
This PR switches the CI workflow to GH actions.
> Switch to github actions

- dashboards/apiserver.libsonnet
- dashboards/controller-manager.libsonnet
- dashboards/kubelet.libsonnet
- dashboards/network-usage/cluster-total.libsonnet
- dashboards/network-usage/namespace-by-pod.libsonnet
- dashboards/network-usage/namespace-by-workload.libsonnet
- dashboards/network-usage/pod-total.libsonnet
- dashboards/network-usage/workload-total.libsonnet
- dashboards/proxy.libsonnet
- dashboards/scheduler.libsonnet
This is just a continuation of #681, and picking up a few dashboards that were overlooked.
> Set Data source template variable label to 'Data Source' for overlooked dashboards

- dashboards/kubelet.libsonnet
> update Containers panel name

- README.md
> chore: Update test section in README

- README.md
Cut new branch to maintain v0.10.
> chore: cut release-0.10 branch

- rules/apps.libsonnet
Fixes #729 
https://github.com/prometheus-operator/kube-prometheus/pull/1564
https://github.com/prometheus-community/helm-charts/pull/1628
> add workload_type: job

- rules/kube_apiserver.libsonnet
Follow-up PR to the effort started in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/722.
Based on sig-scalability SLOs https://github.com/kubernetes/community/blob/master/sig-scalability/slos/api_call_latency.md, we need to exclude streaming read requests when calculating the number of slow requests as they weren't taken into account when defining the latency thresholds.
Sig-scalability didn't mention streaming for write requests, but after discussing that with @aojea, we figured that we most likely want to do the same for write requests since we don't want to take into account long-running write requests such as the following one:
```
kubectl exec pod -- sh
```
Fixes #720 
/cc @dohnto @povilasv
> Exclude long-running requests from KubeAPIErrorBudgetBurn calculation

- README.md
Signed-off-by: Tamal Saha <tamal@appscode.com>
> Update jb install command

- alerts/kubelet.libsonnet
- alerts/system_alerts.libsonnet
- rules/node.libsonnet
More fixes like #752 for multi cluster labels which can cause issues if labels overlap.
> Fix multicluster labels

- alerts/storage_alerts.libsonnet
- tests.yaml
Based on KubePersistentVolumeFillingUp and #427.
> Add inodes alert

- Makefile
No breaking change, simply use variables instead of hard-coded strings. Overriding output directory should be as easy as:
```bash
OUT_DIR=out make
```
> Allow overriding output directory name

- .github/workflows/check-with-upstream.yaml
- .github/workflows/ci.yaml
- Makefile
- scripts/check-selectors-ksm.sh
* Currently implemented for KSM metrics only.
* Also removed dependency of certain workflows on Go.
> Automate checking for missing selectors

- README.md
Adds `release-0.13` to the release table.
> release: Update README with release-0.13

- .github/workflows/check-with-upstream.yaml
- .github/workflows/ci.yaml
GitHub Actions security audit:
- https://woodruffw.github.io/zizmor/audits/#excessive-permissions
- https://github.com/GitHubSecurityLab/actions-permissions
> ci: check action permissions

- alerts/kubelet.libsonnet
- tests/kubelet-test.yaml
> Protect KubeletPodStartUpLatencyHigh against duplicate series
